//! Bosses database generated from GameAreaParam.param.xml
//! This file is auto-generated by scripts/generate_db.py - do not edit manually

use once_cell::sync::Lazy;
use std::collections::HashMap;

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum BossType {
    Demigod,
    GreatBoss,
    Boss,
    Miniboss,
    Unknown,
}

impl BossType {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Demigod => "Demigod",
            Self::GreatBoss => "Great Boss",
            Self::Boss => "Boss",
            Self::Miniboss => "Miniboss",
            Self::Unknown => "Unknown",
        }
    }
}

#[derive(Debug, Clone)]
pub struct BossData {
    pub id: u32,
    pub name: &'static str,
    pub defeat_flag: u32,
    pub region: &'static str,
    pub boss_type: BossType,
    pub runes: u32,
    pub pos_x: f32,
    pub pos_y: f32,
    pub pos_z: f32,
    pub area_no: u8,
    pub block_no: u8,
    pub found_flag: u32,
    pub challenge_flag: u32,
    // Enrichment
    pub mapgenie_id: Option<&'static str>,
}

/// Bosses database (205 entries)
pub static BOSSES_DATA: Lazy<HashMap<u32, BossData>> = Lazy::new(|| {
    let mut m = HashMap::new();
    m.insert(10000800, BossData { id: 10000800, name: "Godrick the Grafted", defeat_flag: 10000800, region: "Stormveil Castle", boss_type: BossType::Demigod, runes: 20000, pos_x: -233.64, pos_y: 73.69, pos_z: 349.60, area_no: 10, block_no: 0, found_flag: 10000801, challenge_flag: 0, mapgenie_id: Some("164421"), });
    m.insert(10000850, BossData { id: 10000850, name: "Margit the Fell Omen", defeat_flag: 10000850, region: "Stormveil Castle", boss_type: BossType::Miniboss, runes: 12000, pos_x: -16.94, pos_y: -2.75, pos_z: -17.60, area_no: 10, block_no: 0, found_flag: 10000851, challenge_flag: 0, mapgenie_id: Some("163938"), });
    m.insert(10010800, BossData { id: 10010800, name: "Grafted Scion", defeat_flag: 10010800, region: "Chapel of Anticipation", boss_type: BossType::Miniboss, runes: 3200, pos_x: -16.94, pos_y: -2.75, pos_z: -17.60, area_no: 10, block_no: 1, found_flag: 10000851, challenge_flag: 0, mapgenie_id: None, });
    m.insert(11000800, BossData { id: 11000800, name: "Morgott, the Omen King", defeat_flag: 11000800, region: "Leyndell- Royal Capital", boss_type: BossType::Demigod, runes: 120000, pos_x: 67.41, pos_y: 79.00, pos_z: -455.18, area_no: 11, block_no: 0, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("176808"), });
    m.insert(11000850, BossData { id: 11000850, name: "Godfrey, First Elden Lord", defeat_flag: 11000850, region: "Leyndell- Royal Capital", boss_type: BossType::Boss, runes: 80000, pos_x: -131.56, pos_y: 31.01, pos_z: -386.36, area_no: 11, block_no: 0, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("176583"), });
    m.insert(11050800, BossData { id: 11050800, name: "Hoarah Loux", defeat_flag: 11050800, region: "Leyndell Ashen Capital", boss_type: BossType::GreatBoss, runes: 300000, pos_x: 41.02, pos_y: 65.12, pos_z: -421.28, area_no: 11, block_no: 5, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(11050850, BossData { id: 11050850, name: "Sir Gideon Ofnir", defeat_flag: 11050850, region: "Leyndell Ashen Capital", boss_type: BossType::GreatBoss, runes: 150000, pos_x: -132.34, pos_y: 31.03, pos_z: -386.62, area_no: 11, block_no: 5, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("176583"), });
    m.insert(12010800, BossData { id: 12010800, name: "Dragonkin Soldier of Nokstella", defeat_flag: 12010800, region: "Ainsel River", boss_type: BossType::Miniboss, runes: 12000, pos_x: -193.00, pos_y: -224.50, pos_z: 59.76, area_no: 12, block_no: 1, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(12010850, BossData { id: 12010850, name: "Dragonkin Soldier (Lake of Rot)", defeat_flag: 12010850, region: "Ainsel River", boss_type: BossType::Boss, runes: 58000, pos_x: -224.54, pos_y: -317.06, pos_z: -306.44, area_no: 12, block_no: 1, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(12020390, BossData { id: 12030390, name: "Crucible Knight", defeat_flag: 12020390, region: "Deeproot Depths", boss_type: BossType::Miniboss, runes: 25000, pos_x: -884.21, pos_y: 96.72, pos_z: -320.67, area_no: 12, block_no: 3, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(12020800, BossData { id: 12020800, name: "Valiant Gargoyles", defeat_flag: 12020800, region: "Siofra River", boss_type: BossType::Boss, runes: 30000, pos_x: 1213.21, pos_y: -619.69, pos_z: 1934.45, area_no: 12, block_no: 2, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(12020830, BossData { id: 12020830, name: "Dragonkin Soldier of Nokron", defeat_flag: 12020830, region: "Siofra River", boss_type: BossType::Miniboss, runes: 16000, pos_x: 1240.10, pos_y: -748.45, pos_z: 1738.16, area_no: 12, block_no: 2, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(12020850, BossData { id: 12020850, name: "Mimic Tear", defeat_flag: 12020850, region: "Siofra River", boss_type: BossType::Miniboss, runes: 10000, pos_x: 995.94, pos_y: -617.50, pos_z: 1146.54, area_no: 12, block_no: 2, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(12030800, BossData { id: 12030800, name: "Fia's Champion", defeat_flag: 12030800, region: "Deeproot Depths", boss_type: BossType::Boss, runes: 40000, pos_x: -370.11, pos_y: 149.47, pos_z: -203.44, area_no: 12, block_no: 3, found_flag: 30020800, challenge_flag: 0, mapgenie_id: None, });
    m.insert(12030850, BossData { id: 12030850, name: "Lichdragon Fortissax", defeat_flag: 12030850, region: "Deeproot Depths", boss_type: BossType::Boss, runes: 90000, pos_x: -448.77, pos_y: 149.34, pos_z: -273.11, area_no: 12, block_no: 3, found_flag: 30020800, challenge_flag: 12032859, mapgenie_id: Some("168158"), });
    m.insert(12040800, BossData { id: 12040800, name: "Astel Naturalborn of the Void", defeat_flag: 12040800, region: "Ainsel River", boss_type: BossType::Boss, runes: 80000, pos_x: -100.00, pos_y: -106.23, pos_z: -125.00, area_no: 12, block_no: 4, found_flag: 30020800, challenge_flag: 0, mapgenie_id: Some("170308"), });
    m.insert(12050800, BossData { id: 12050800, name: "Mohg Lord of Blood", defeat_flag: 12050800, region: "Mohgwyn Palace", boss_type: BossType::Demigod, runes: 420000, pos_x: 1552.51, pos_y: -505.78, pos_z: 1234.42, area_no: 12, block_no: 5, found_flag: 30020800, challenge_flag: 0, mapgenie_id: Some("169764"), });
    m.insert(12080800, BossData { id: 12080800, name: "Ancestor Spirit", defeat_flag: 12080800, region: "Siofra River", boss_type: BossType::Miniboss, runes: 13000, pos_x: 1530.68, pos_y: -1735.68, pos_z: -1052.55, area_no: 12, block_no: 8, found_flag: 30020800, challenge_flag: 0, mapgenie_id: None, });
    m.insert(12090800, BossData { id: 12090800, name: "Regal Ancestor Spirit", defeat_flag: 12090800, region: "Nokron Eternal City", boss_type: BossType::Miniboss, runes: 24000, pos_x: 1184.79, pos_y: -1538.52, pos_z: 1899.71, area_no: 12, block_no: 9, found_flag: 30020800, challenge_flag: 0, mapgenie_id: None, });
    m.insert(13000800, BossData { id: 13000800, name: "Maliketh, the Black Blade", defeat_flag: 13000800, region: "Crumbling Farum Azula", boss_type: BossType::GreatBoss, runes: 220000, pos_x: 197.21, pos_y: -32.52, pos_z: 374.75, area_no: 13, block_no: 0, found_flag: 30020800, challenge_flag: 0, mapgenie_id: Some("169007"), });
    m.insert(13000830, BossData { id: 13000830, name: "Dragonlord Placidusax", defeat_flag: 13000830, region: "Crumbling Farum Azula", boss_type: BossType::GreatBoss, runes: 280000, pos_x: 14.45, pos_y: 1009.59, pos_z: 329.50, area_no: 13, block_no: 0, found_flag: 30020800, challenge_flag: 0, mapgenie_id: Some("168522"), });
    m.insert(13000850, BossData { id: 13000850, name: "Godskin Duo", defeat_flag: 13000850, region: "Crumbling Farum Azula", boss_type: BossType::GreatBoss, runes: 170000, pos_x: -3.55, pos_y: -52.20, pos_z: 406.52, area_no: 13, block_no: 0, found_flag: 30020800, challenge_flag: 0, mapgenie_id: Some("167392"), });
    m.insert(14000800, BossData { id: 14000800, name: "Rennala Queen of the Full Moon", defeat_flag: 14000800, region: "Academy of Raya Lucaria", boss_type: BossType::Demigod, runes: 40000, pos_x: 70.40, pos_y: -838.71, pos_z: -23.42, area_no: 14, block_no: 0, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("164430"), });
    m.insert(14000850, BossData { id: 14000850, name: "Red Wolf of Radagon", defeat_flag: 14000850, region: "Academy of Raya Lucaria", boss_type: BossType::Miniboss, runes: 14000, pos_x: 151.24, pos_y: 110.57, pos_z: -222.99, area_no: 14, block_no: 0, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("165697"), });
    m.insert(15000800, BossData { id: 15000800, name: "Malenia Blade of Miquella", defeat_flag: 15000800, region: "Miquella's Haligtree", boss_type: BossType::Demigod, runes: 480000, pos_x: -25.87, pos_y: 51.95, pos_z: 477.41, area_no: 15, block_no: 0, found_flag: 0, challenge_flag: 0, mapgenie_id: Some("176825"), });
    m.insert(15000850, BossData { id: 15000850, name: "Loretta Knight of the Haligtree", defeat_flag: 15000850, region: "Miquella's Haligtree", boss_type: BossType::GreatBoss, runes: 200000, pos_x: 174.37, pos_y: 431.66, pos_z: 307.90, area_no: 15, block_no: 0, found_flag: 0, challenge_flag: 0, mapgenie_id: Some("168228"), });
    m.insert(16000800, BossData { id: 16000800, name: "Rykard Lord of Blasphemy", defeat_flag: 16000800, region: "Volcano Manor", boss_type: BossType::Demigod, runes: 130000, pos_x: 93.69, pos_y: -438.87, pos_z: -118.41, area_no: 16, block_no: 0, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("167571"), });
    m.insert(16000850, BossData { id: 16000850, name: "Godskin Noble", defeat_flag: 16000850, region: "Volcano Manor", boss_type: BossType::Boss, runes: 50000, pos_x: 62.32, pos_y: 7.82, pos_z: -211.48, area_no: 16, block_no: 0, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("168177"), });
    m.insert(16000860, BossData { id: 16000860, name: "Abductor Virgins", defeat_flag: 16000860, region: "Volcano Manor", boss_type: BossType::Miniboss, runes: 10000, pos_x: 229.67, pos_y: -133.52, pos_z: -251.97, area_no: 16, block_no: 0, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(18000800, BossData { id: 18000800, name: "Crucible Illusion", defeat_flag: 18000800, region: "Stranded Graveyard", boss_type: BossType::Miniboss, runes: 15000, pos_x: 29.50, pos_y: -111.57, pos_z: 53.47, area_no: 18, block_no: 0, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(18000850, BossData { id: 18000850, name: "Soldier of Godrick", defeat_flag: 18000850, region: "Stranded Graveyard", boss_type: BossType::Miniboss, runes: 400, pos_x: -40.94, pos_y: 10.67, pos_z: 41.10, area_no: 18, block_no: 0, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("164420"), });
    m.insert(19000800, BossData { id: 19000800, name: "Elden Beast", defeat_flag: 19000800, region: "Stone Platform", boss_type: BossType::GreatBoss, runes: 500000, pos_x: 213.99, pos_y: -719.98, pos_z: -686.97, area_no: 19, block_no: 0, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(20000800, BossData { id: 20000800, name: "Divine Beast Dancing Lion", defeat_flag: 20000800, region: "Belurat, Tower Settlement", boss_type: BossType::GreatBoss, runes: 120000, pos_x: -43.02, pos_y: 118.48, pos_z: 336.61, area_no: 20, block_no: 0, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(20010800, BossData { id: 20010800, name: "Promised Consort Radahn", defeat_flag: 20010800, region: "Enir-Ilim", boss_type: BossType::GreatBoss, runes: 500000, pos_x: -287.24, pos_y: 299.70, pos_z: -141.21, area_no: 20, block_no: 1, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(21000850, BossData { id: 21000850, name: "Golden Hippopotamus", defeat_flag: 21000850, region: "Shadow Keep", boss_type: BossType::GreatBoss, runes: 200000, pos_x: -25.87, pos_y: 51.95, pos_z: 477.41, area_no: 15, block_no: 0, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(21010800, BossData { id: 21010800, name: "Messmer the Impaler", defeat_flag: 21010800, region: "Specimen Storehouse", boss_type: BossType::GreatBoss, runes: 400000, pos_x: 174.37, pos_y: 431.66, pos_z: 307.90, area_no: 15, block_no: 0, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(22000800, BossData { id: 22000800, name: "Putrescent Knight", defeat_flag: 22000800, region: "Stone Coffin Fissure", boss_type: BossType::GreatBoss, runes: 220000, pos_x: -70.10, pos_y: -295.01, pos_z: 104.29, area_no: 22, block_no: 0, found_flag: 22000801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(25000800, BossData { id: 25000800, name: "Metyr, Mother of Fingers", defeat_flag: 25000800, region: "Finger Birthing Grounds", boss_type: BossType::GreatBoss, runes: 420000, pos_x: 4.32, pos_y: 0.01, pos_z: -2.32, area_no: 25, block_no: 0, found_flag: 30020800, challenge_flag: 0, mapgenie_id: None, });
    m.insert(28000800, BossData { id: 28000800, name: "Midra, Lord of Frenzied Flame", defeat_flag: 28000800, region: "Midra's Manse", boss_type: BossType::GreatBoss, runes: 410000, pos_x: -11.75, pos_y: 16.01, pos_z: -92.36, area_no: 28, block_no: 0, found_flag: 28000801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(30000800, BossData { id: 30000800, name: "Cemetery Shade", defeat_flag: 30000800, region: "Tombsward Catacombs", boss_type: BossType::Miniboss, runes: 2200, pos_x: 2.62, pos_y: 46.74, pos_z: 65.56, area_no: 30, block_no: 0, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("165321"), });
    m.insert(30010800, BossData { id: 30010800, name: "Erdtree Burial Watchdog", defeat_flag: 30010800, region: "Impaler's Catacombs", boss_type: BossType::Miniboss, runes: 2400, pos_x: -34.14, pos_y: 23.12, pos_z: -156.39, area_no: 30, block_no: 1, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("165949"), });
    m.insert(30020800, BossData { id: 30020800, name: "Erdtree Burial Watchdog", defeat_flag: 30020800, region: "Stormfoot Catacombs", boss_type: BossType::Miniboss, runes: 1300, pos_x: 103.67, pos_y: 94.93, pos_z: 74.18, area_no: 30, block_no: 2, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("166628"), });
    m.insert(30030800, BossData { id: 30030800, name: "Spirit-Caller Snail", defeat_flag: 30030800, region: "Road's End Catacombs", boss_type: BossType::Miniboss, runes: 3000, pos_x: 90.50, pos_y: 193.71, pos_z: 24.29, area_no: 30, block_no: 3, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(30040800, BossData { id: 30040800, name: "Grave Warden Duelist", defeat_flag: 30040800, region: "Murkwater Catacombs", boss_type: BossType::Miniboss, runes: 1700, pos_x: -20.41, pos_y: 46.12, pos_z: 98.52, area_no: 30, block_no: 4, found_flag: 30040801, challenge_flag: 0, mapgenie_id: Some("165457"), });
    m.insert(30050800, BossData { id: 30050800, name: "Cemetery Shade", defeat_flag: 30050800, region: "Black Knife Catacombs", boss_type: BossType::Miniboss, runes: 3500, pos_x: -189.41, pos_y: 406.20, pos_z: 121.21, area_no: 30, block_no: 5, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(30050850, BossData { id: 30050850, name: "Black Knife Assassin", defeat_flag: 30050850, region: "Black Knife Catacombs", boss_type: BossType::Miniboss, runes: 4200, pos_x: -225.78, pos_y: 411.53, pos_z: 16.87, area_no: 30, block_no: 5, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(30060800, BossData { id: 30060800, name: "Erdtree Burial Watchdog", defeat_flag: 30060800, region: "Cliffbottom Catacombs", boss_type: BossType::Miniboss, runes: 3200, pos_x: 20.86, pos_y: 194.32, pos_z: -18.72, area_no: 30, block_no: 6, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(30070800, BossData { id: 30070800, name: "Erdtree Burial Watchdog", defeat_flag: 30070800, region: "Wyndham Catacombs", boss_type: BossType::Miniboss, runes: 12000, pos_x: -127.12, pos_y: 820.61, pos_z: 221.81, area_no: 30, block_no: 7, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(30080800, BossData { id: 30080800, name: "Ancient Hero of Zamor", defeat_flag: 30080800, region: "Sainted Hero's Grave", boss_type: BossType::Miniboss, runes: 20000, pos_x: 336.11, pos_y: 742.22, pos_z: 13.74, area_no: 30, block_no: 8, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(30090800, BossData { id: 30090800, name: "Red Wolf of the Champion", defeat_flag: 30090800, region: "Gelmir Hero's Grave", boss_type: BossType::Miniboss, runes: 21000, pos_x: -148.10, pos_y: 646.26, pos_z: 97.02, area_no: 30, block_no: 9, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(30100800, BossData { id: 30100800, name: "Crucible Knight Ordovis", defeat_flag: 30100800, region: "Auriza Hero's Grave", boss_type: BossType::Miniboss, runes: 28000, pos_x: -108.85, pos_y: 761.46, pos_z: 343.72, area_no: 30, block_no: 10, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(30110800, BossData { id: 30110800, name: "Black Knife Assassin", defeat_flag: 30110800, region: "Deathtouched Catacombs", boss_type: BossType::Miniboss, runes: 1600, pos_x: -208.78, pos_y: 177.50, pos_z: 23.67, area_no: 30, block_no: 11, found_flag: 30030801, challenge_flag: 0, mapgenie_id: Some("165600"), });
    m.insert(30120800, BossData { id: 30120800, name: "Perfumer Tricia", defeat_flag: 30120800, region: "Unsightly Catacombs", boss_type: BossType::Miniboss, runes: 9400, pos_x: 7.63, pos_y: 618.32, pos_z: 235.84, area_no: 30, block_no: 12, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(30130800, BossData { id: 30130800, name: "Grave Warden Duelist", defeat_flag: 30130800, region: "Auriza Side Tomb", boss_type: BossType::Miniboss, runes: 15000, pos_x: 4.35, pos_y: 954.42, pos_z: 78.96, area_no: 30, block_no: 13, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(30140800, BossData { id: 30140800, name: "Erdtree Burial Watchdog", defeat_flag: 30140800, region: "Minor Erdtree Catacombs", boss_type: BossType::Miniboss, runes: 7400, pos_x: -123.40, pos_y: 73.12, pos_z: -33.96, area_no: 30, block_no: 14, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(30150800, BossData { id: 30150800, name: "Cemetery Shade", defeat_flag: 30150800, region: "Caelid Catacombs", boss_type: BossType::Miniboss, runes: 6800, pos_x: 125.71, pos_y: 24.22, pos_z: 258.03, area_no: 30, block_no: 15, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(30160800, BossData { id: 30160800, name: "Putrid Tree Spirit", defeat_flag: 30160800, region: "War-Dead Catacombs", boss_type: BossType::Boss, runes: 64000, pos_x: -127.39, pos_y: -25.24, pos_z: -89.49, area_no: 30, block_no: 16, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(30170800, BossData { id: 30170800, name: "Ancient Hero of Zamor", defeat_flag: 30170800, region: "Giant-Conquering Hero's Grave", boss_type: BossType::Boss, runes: 83000, pos_x: -7.61, pos_y: 1451.72, pos_z: -35.84, area_no: 30, block_no: 17, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(30180800, BossData { id: 30180800, name: "Ulcerated Tree Sprit", defeat_flag: 30180800, region: "Giants' Mountaintop Catacombs", boss_type: BossType::Boss, runes: 48000, pos_x: -134.19, pos_y: 1478.18, pos_z: 156.62, area_no: 30, block_no: 18, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(30190800, BossData { id: 30190800, name: "Putrid Grave Warden Duelist", defeat_flag: 30190800, region: "Consecrated Snowfield Catacombs", boss_type: BossType::Boss, runes: 78000, pos_x: 68.30, pos_y: 1374.72, pos_z: -160.63, area_no: 30, block_no: 19, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(30200810, BossData { id: 30200800, name: "Stray Mimic Tear", defeat_flag: 30200810, region: "Hidden Path to the Haligtree", boss_type: BossType::Boss, runes: 50000, pos_x: -89.69, pos_y: 1278.32, pos_z: -264.39, area_no: 30, block_no: 20, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(31000800, BossData { id: 31000800, name: "Patches", defeat_flag: 31000800, region: "Murkwater Cave", boss_type: BossType::Miniboss, runes: 0, pos_x: -140.26, pos_y: -10.88, pos_z: 42.92, area_no: 31, block_no: 0, found_flag: 0, challenge_flag: 0, mapgenie_id: Some("164504"), });
    m.insert(31010800, BossData { id: 31010800, name: "Runebear", defeat_flag: 31010800, region: "Earthbore Cave", boss_type: BossType::Miniboss, runes: 2600, pos_x: -143.90, pos_y: -39.81, pos_z: -146.57, area_no: 31, block_no: 1, found_flag: 0, challenge_flag: 0, mapgenie_id: Some("164828"), });
    m.insert(31020800, BossData { id: 31020800, name: "Miranda the Blighted Bloom", defeat_flag: 31020800, region: "Tombsward Cave", boss_type: BossType::Miniboss, runes: 2100, pos_x: -117.18, pos_y: 29.54, pos_z: 0.91, area_no: 31, block_no: 2, found_flag: 31020801, challenge_flag: 0, mapgenie_id: Some("165743"), });
    m.insert(31030800, BossData { id: 31030800, name: "Beastman of Farum Azula", defeat_flag: 31030800, region: "Groveside Cave", boss_type: BossType::Miniboss, runes: 1000, pos_x: -120.79, pos_y: 88.28, pos_z: 80.77, area_no: 31, block_no: 3, found_flag: 31030801, challenge_flag: 0, mapgenie_id: Some("164476"), });
    m.insert(31040800, BossData { id: 31040800, name: "Cleanrot Knight", defeat_flag: 31040800, region: "Stillwater Cave", boss_type: BossType::Miniboss, runes: 3300, pos_x: 97.86, pos_y: 199.75, pos_z: -166.72, area_no: 31, block_no: 4, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(31050800, BossData { id: 31050800, name: "Bloodhound Knight", defeat_flag: 31050800, region: "Lakeside Crystal Cave", boss_type: BossType::Miniboss, runes: 3600, pos_x: -166.70, pos_y: 154.45, pos_z: -18.60, area_no: 31, block_no: 5, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(31060800, BossData { id: 31060800, name: "Crystalians", defeat_flag: 31060800, region: "Academy Crystal Cave", boss_type: BossType::Miniboss, runes: 3300, pos_x: 191.16, pos_y: 216.71, pos_z: 104.37, area_no: 31, block_no: 6, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(31070800, BossData { id: 31070800, name: "Kindred of Rot", defeat_flag: 31070800, region: "Seethewater Cave", boss_type: BossType::Miniboss, runes: 10000, pos_x: -127.26, pos_y: 719.75, pos_z: 260.21, area_no: 31, block_no: 7, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(31090800, BossData { id: 31090800, name: "Demi-Human Queen Margot", defeat_flag: 31090800, region: "Volcano Cave", boss_type: BossType::Miniboss, runes: 11000, pos_x: -63.91, pos_y: 1013.07, pos_z: -75.07, area_no: 31, block_no: 9, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(31100800, BossData { id: 31100800, name: "Beastman of Farum Azula", defeat_flag: 31100800, region: "Dragonbarrow Cave", boss_type: BossType::Boss, runes: 65000, pos_x: 30.65, pos_y: 104.56, pos_z: 19.06, area_no: 31, block_no: 10, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(31110800, BossData { id: 31110800, name: "Crystalians", defeat_flag: 31110800, region: "Sellia Hideaway", boss_type: BossType::Miniboss, runes: 7100, pos_x: -145.79, pos_y: 126.94, pos_z: 135.72, area_no: 31, block_no: 11, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(31120800, BossData { id: 31120800, name: "Misbegotten Crusader", defeat_flag: 31120800, region: "Cave of the Forlorn", boss_type: BossType::Boss, runes: 93000, pos_x: -23.02, pos_y: 1193.38, pos_z: 112.95, area_no: 31, block_no: 12, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(31150800, BossData { id: 31150800, name: "Demi-Human Chief", defeat_flag: 31150800, region: "Coastal Cave", boss_type: BossType::Miniboss, runes: 1200, pos_x: 30.89, pos_y: -29.31, pos_z: -99.84, area_no: 31, block_no: 15, found_flag: 31150801, challenge_flag: 0, mapgenie_id: Some("164457"), });
    m.insert(31170800, BossData { id: 31170800, name: "Guardian Golem", defeat_flag: 31170800, region: "Highroad Cave", boss_type: BossType::Miniboss, runes: 1700, pos_x: 74.42, pos_y: -9.66, pos_z: 148.68, area_no: 31, block_no: 17, found_flag: 31170801, challenge_flag: 0, mapgenie_id: Some("164509"), });
    m.insert(31180800, BossData { id: 31180800, name: "Omenkiller", defeat_flag: 31180800, region: "Perfumer's Grotto", boss_type: BossType::Miniboss, runes: 8400, pos_x: -94.34, pos_y: 790.80, pos_z: 181.71, area_no: 31, block_no: 18, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(31190800, BossData { id: 31190800, name: "Black Knife Assassin", defeat_flag: 31190800, region: "Sage's Cave", boss_type: BossType::Miniboss, runes: 9000, pos_x: 130.99, pos_y: 623.49, pos_z: -12.70, area_no: 31, block_no: 19, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(31190850, BossData { id: 31190850, name: "Necromancer Garris", defeat_flag: 31190850, region: "Sage's Cave", boss_type: BossType::Miniboss, runes: 9000, pos_x: 108.33, pos_y: 627.26, pos_z: -45.19, area_no: 31, block_no: 19, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(31200800, BossData { id: 31200800, name: "Cleanrot Knight", defeat_flag: 31200800, region: "Abandoned Cave", boss_type: BossType::Miniboss, runes: 7000, pos_x: 166.15, pos_y: 86.27, pos_z: 149.84, area_no: 31, block_no: 20, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(31210800, BossData { id: 31210800, name: "Frenzied Duelist", defeat_flag: 31210800, region: "Gaol Cave", boss_type: BossType::Miniboss, runes: 6700, pos_x: -164.04, pos_y: 12.10, pos_z: 56.99, area_no: 31, block_no: 21, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(31220800, BossData { id: 31220800, name: "Spirit-Caller Snail", defeat_flag: 31220800, region: "Spiritcaller's Cave", boss_type: BossType::Boss, runes: 70000, pos_x: -45.51, pos_y: 1579.18, pos_z: -118.10, area_no: 31, block_no: 22, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(32000800, BossData { id: 32000800, name: "Scaly Misbegotten", defeat_flag: 32000800, region: "Morne Tunnel", boss_type: BossType::Miniboss, runes: 2000, pos_x: 83.34, pos_y: -24.53, pos_z: -24.24, area_no: 32, block_no: 0, found_flag: 32010801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(32010800, BossData { id: 32010800, name: "Stonedigger Troll", defeat_flag: 32010800, region: "Limgrave Tunnels", boss_type: BossType::Miniboss, runes: 1800, pos_x: 26.05, pos_y: -30.45, pos_z: -1.28, area_no: 32, block_no: 1, found_flag: 32010801, challenge_flag: 0, mapgenie_id: Some("164472"), });
    m.insert(32020800, BossData { id: 32020800, name: "Crystalian (Ringblade)", defeat_flag: 32020800, region: "Raya Lucaria Crystal Tunnel", boss_type: BossType::Miniboss, runes: 3000, pos_x: 12.50, pos_y: 110.38, pos_z: 19.45, area_no: 32, block_no: 2, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(32040800, BossData { id: 32040800, name: "Stonedigger Troll", defeat_flag: 32040800, region: "Old Altus Tunnel", boss_type: BossType::Miniboss, runes: 9600, pos_x: -299.12, pos_y: 677.13, pos_z: -120.37, area_no: 32, block_no: 4, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(32050800, BossData { id: 32050800, name: "Crystalian (Ringblade)", defeat_flag: 32050800, region: "Altus Tunnel", boss_type: BossType::Miniboss, runes: 9000, pos_x: 56.44, pos_y: 777.25, pos_z: -35.13, area_no: 32, block_no: 5, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(32070800, BossData { id: 32070800, name: "Magma Wyrm", defeat_flag: 32070800, region: "Gael Tunnel", boss_type: BossType::Miniboss, runes: 7500, pos_x: -24.17, pos_y: 89.93, pos_z: 162.44, area_no: 32, block_no: 7, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(32080800, BossData { id: 32080800, name: "Fallingstar Beast", defeat_flag: 32080800, region: "Sellia Crystal Tunnel", boss_type: BossType::Miniboss, runes: 7600, pos_x: -75.63, pos_y: 124.56, pos_z: 231.96, area_no: 32, block_no: 8, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(32110800, BossData { id: 32110800, name: "Astel, Stars of Darkness", defeat_flag: 32110800, region: "Yelough Anix Tunnel", boss_type: BossType::GreatBoss, runes: 120000, pos_x: 49.48, pos_y: 1210.79, pos_z: 86.20, area_no: 32, block_no: 11, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(34120800, BossData { id: 34120800, name: "Onyx Lord", defeat_flag: 34120800, region: "Divine Tower of West Altus", boss_type: BossType::Miniboss, runes: 16000, pos_x: -49.46, pos_y: 711.36, pos_z: -195.92, area_no: 34, block_no: 12, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(34130800, BossData { id: 34130800, name: "Godskin Apostle", defeat_flag: 34130800, region: "Divine Tower of Caelid", boss_type: BossType::Boss, runes: 94000, pos_x: 76.83, pos_y: 36.31, pos_z: -101.86, area_no: 34, block_no: 13, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(34140850, BossData { id: 34140850, name: "Fell Twins", defeat_flag: 34140850, region: "Divine Tower of East Altus", boss_type: BossType::Miniboss, runes: 29000, pos_x: 572.70, pos_y: -373.48, pos_z: -321.00, area_no: 34, block_no: 14, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(35000800, BossData { id: 35000800, name: "Mohg The Omen", defeat_flag: 35000800, region: "Subterranean Shunning-Grounds", boss_type: BossType::GreatBoss, runes: 100000, pos_x: 74.54, pos_y: -298.53, pos_z: -80.61, area_no: 35, block_no: 0, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("168657"), });
    m.insert(35000850, BossData { id: 35000850, name: "Esgar Priest of Blood", defeat_flag: 35000850, region: "Subterranean Shunning-Grounds", boss_type: BossType::Boss, runes: 30000, pos_x: -203.85, pos_y: -153.85, pos_z: -306.87, area_no: 35, block_no: 0, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(39200800, BossData { id: 39200800, name: "Magma Wyrm Makar", defeat_flag: 39200800, region: "Ruin-Strewn Precipice", boss_type: BossType::Miniboss, runes: 24000, pos_x: -106.67, pos_y: 353.66, pos_z: -1310.49, area_no: 39, block_no: 20, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(40000800, BossData { id: 40000800, name: "Death Knight", defeat_flag: 40000800, region: "Fog Rift Catacombs", boss_type: BossType::GreatBoss, runes: 110000, pos_x: -426.56, pos_y: 113.72, pos_z: -33.97, area_no: 40, block_no: 0, found_flag: 40000801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(40010800, BossData { id: 40010800, name: "Death Knight", defeat_flag: 40010800, region: "Scorpion River Catacombs", boss_type: BossType::GreatBoss, runes: 130000, pos_x: 186.63, pos_y: 149.72, pos_z: -139.03, area_no: 40, block_no: 1, found_flag: 40010801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(41000800, BossData { id: 41000800, name: "Demi-Human Swordmaster Onze", defeat_flag: 41000800, region: "Belurat Gaol", boss_type: BossType::Boss, runes: 80000, pos_x: -178.66, pos_y: 78.58, pos_z: -198.63, area_no: 41, block_no: 0, found_flag: 41000801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(41010800, BossData { id: 41010800, name: "Curseblade Labirith", defeat_flag: 41010800, region: "Bonny Gaol", boss_type: BossType::GreatBoss, runes: 100000, pos_x: -194.07, pos_y: 190.58, pos_z: 89.84, area_no: 41, block_no: 1, found_flag: 41000801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(41020800, BossData { id: 41020800, name: "Lamenter", defeat_flag: 41020800, region: "Lamenter's Gaol", boss_type: BossType::GreatBoss, runes: 160000, pos_x: 152.60, pos_y: 19.80, pos_z: -14.96, area_no: 41, block_no: 2, found_flag: 41000801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(43000800, BossData { id: 43000800, name: "Chief Bloodfiend", defeat_flag: 43000800, region: "Rivermouth Cave", boss_type: BossType::Boss, runes: 80000, pos_x: 134.53, pos_y: 116.28, pos_z: 138.68, area_no: 43, block_no: 0, found_flag: 43000801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(43010800, BossData { id: 43010800, name: "Ancient Dragon-man", defeat_flag: 43010800, region: "Dragon's Pit", boss_type: BossType::GreatBoss, runes: 130000, pos_x: 37.56, pos_y: 94.02, pos_z: 4.20, area_no: 43, block_no: 1, found_flag: 43010801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1033420800, BossData { id: 1033420800, name: "Alecto Black Knife Ringleader", defeat_flag: 1033420800, region: "Liurnia - Moonlight Altar", boss_type: BossType::Boss, runes: 80000, pos_x: -40.57, pos_y: 346.70, pos_z: 86.24, area_no: 60, block_no: 33, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("171212"), });
    m.insert(1033430800, BossData { id: 1033430800, name: "Erdtree Avatar", defeat_flag: 1033430800, region: "Liurnia - Minor Erdtree", boss_type: BossType::Miniboss, runes: 5800, pos_x: 43.42, pos_y: 291.36, pos_z: 28.77, area_no: 60, block_no: 33, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1033450800, BossData { id: 1033450800, name: "Bols Carian Knight", defeat_flag: 1033450800, region: "Liurnia - Cuckoo's Evergaol", boss_type: BossType::Miniboss, runes: 4600, pos_x: -52.30, pos_y: 245.05, pos_z: -29.60, area_no: 60, block_no: 33, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1034420800, BossData { id: 1034420800, name: "Glintstone Dragon Adula", defeat_flag: 1034420800, region: "Liurnia - Moonfolk Ruins", boss_type: BossType::GreatBoss, runes: 120000, pos_x: 101.58, pos_y: 397.27, pos_z: -42.53, area_no: 60, block_no: 34, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1034450800, BossData { id: 1034450800, name: "Glintstone Dragon Smarag", defeat_flag: 1034450800, region: "Liurnia - Meeting Place", boss_type: BossType::Miniboss, runes: 14000, pos_x: -8.09, pos_y: 237.38, pos_z: -10.62, area_no: 60, block_no: 34, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1034480800, BossData { id: 1034480800, name: "Royal Revenant", defeat_flag: 1034480800, region: "Liurnia - Kingsrealm Ruins", boss_type: BossType::Miniboss, runes: 3100, pos_x: 46.25, pos_y: 252.21, pos_z: 77.03, area_no: 60, block_no: 34, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1034500800, BossData { id: 1034500800, name: "Glintstone Dragon Adula", defeat_flag: 1034500800, region: "Liurnia - Ranni's Rise", boss_type: BossType::Miniboss, runes: 12000, pos_x: 76.01, pos_y: 440.94, pos_z: 63.31, area_no: 60, block_no: 34, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1035420800, BossData { id: 1035420800, name: "Omenkiller", defeat_flag: 1035420800, region: "Liurnia - Albinauric Village", boss_type: BossType::Miniboss, runes: 4900, pos_x: -38.61, pos_y: 269.17, pos_z: -17.90, area_no: 60, block_no: 35, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1035500800, BossData { id: 1035500800, name: "Loretta, Royal Knight", defeat_flag: 1035500800, region: "Liurnia - Caria Manor", boss_type: BossType::Miniboss, runes: 10000, pos_x: -31.85, pos_y: 430.95, pos_z: 100.61, area_no: 60, block_no: 35, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("165490"), });
    m.insert(1035530800, BossData { id: 1035530800, name: "Magma Wyrm", defeat_flag: 1035530800, region: "Mt. Gelmir - Seethewater Terminus", boss_type: BossType::Miniboss, runes: 19000, pos_x: -3.79, pos_y: 824.00, pos_z: -70.69, area_no: 60, block_no: 35, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1036450340, BossData { id: 1036450340, name: "Death Rite Bird", defeat_flag: 1036450340, region: "Liurnia - Gate Town Northwest", boss_type: BossType::Miniboss, runes: 7800, pos_x: -63.61, pos_y: 237.57, pos_z: 36.97, area_no: 60, block_no: 36, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1036480340, BossData { id: 1036480340, name: "Night's Cavalry", defeat_flag: 1036480340, region: "Bellum Highway - East Raya Lucaria Gate", boss_type: BossType::Miniboss, runes: 5600, pos_x: 21.79, pos_y: 321.63, pos_z: 28.79, area_no: 60, block_no: 36, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1036500800, BossData { id: 1036500800, name: "Onyx Lord", defeat_flag: 1036500800, region: "Liurnia - Royal Grave Evergaol", boss_type: BossType::Miniboss, runes: 3600, pos_x: 121.09, pos_y: 379.63, pos_z: 10.94, area_no: 60, block_no: 36, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("166766"), });
    m.insert(1036540800, BossData { id: 1036540800, name: "Fallingstar Beast", defeat_flag: 1036540800, region: "Mt. Gelmir - Ninth Mt. Gelmir Campsite", boss_type: BossType::Miniboss, runes: 21000, pos_x: 100.63, pos_y: 1052.16, pos_z: -41.76, area_no: 60, block_no: 36, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1037420340, BossData { id: 1037420340, name: "Death Rite Bird", defeat_flag: 1037420340, region: "Liurnia - Laskyar Ruins", boss_type: BossType::Miniboss, runes: 6600, pos_x: -51.53, pos_y: 238.31, pos_z: 96.25, area_no: 60, block_no: 37, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1037460800, BossData { id: 1037460800, name: "Bell Bearing Hunter", defeat_flag: 1037460800, region: "Liurnia - Church of Vows", boss_type: BossType::Miniboss, runes: 6000, pos_x: -48.34, pos_y: 398.31, pos_z: 9.79, area_no: 60, block_no: 37, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("182504"), });
    m.insert(1037510800, BossData { id: 1037510800, name: "Ancient Dragon Lansseax", defeat_flag: 1037510800, region: "Altus Plateau - Abandoned Coffin", boss_type: BossType::Boss, runes: 60000, pos_x: 98.54, pos_y: 703.67, pos_z: 29.05, area_no: 60, block_no: 37, found_flag: 30020801, challenge_flag: 1037510300, mapgenie_id: None, });
    m.insert(1037530800, BossData { id: 1037530800, name: "Demi-Human Queen Maggie", defeat_flag: 1037530800, region: "Mt. Gelmir - Primeval Sorcerer Azur", boss_type: BossType::Miniboss, runes: 13000, pos_x: 52.79, pos_y: 903.67, pos_z: -88.34, area_no: 60, block_no: 37, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1037540810, BossData { id: 1037540810, name: "Ulcerated Tree Spirit", defeat_flag: 1037540810, region: "Mt. Gelmir - Minor Erdtree", boss_type: BossType::Miniboss, runes: 18000, pos_x: -33.39, pos_y: 856.80, pos_z: -72.88, area_no: 60, block_no: 37, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1038410800, BossData { id: 1038410800, name: "Adan, Thief of Fire", defeat_flag: 1038410800, region: "Liurnia - Malefactor's Evergaol", boss_type: BossType::Miniboss, runes: 3800, pos_x: 3.89, pos_y: 257.37, pos_z: -124.93, area_no: 60, block_no: 38, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("166505"), });
    m.insert(1038480800, BossData { id: 1038480800, name: "Erdtree Avatar", defeat_flag: 1038480800, region: "Bellum Highway - Minor Erdtree", boss_type: BossType::Miniboss, runes: 5800, pos_x: -30.17, pos_y: 404.20, pos_z: -102.92, area_no: 60, block_no: 38, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1038510800, BossData { id: 1038510800, name: "Demi-Human Queen", defeat_flag: 1038510800, region: "Altus Plateau - Erdtree-Gazing Hill- Lux Ruins", boss_type: BossType::Miniboss, runes: 8500, pos_x: -32.46, pos_y: 770.80, pos_z: 0.54, area_no: 60, block_no: 38, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1038520800, BossData { id: 1038520340, name: "Tibia Mariner", defeat_flag: 1038520800, region: "Altus Plateau - Wyndham Ruins", boss_type: BossType::Miniboss, runes: 14000, pos_x: -127.16, pos_y: 823.41, pos_z: 71.56, area_no: 60, block_no: 38, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1039430340, BossData { id: 1039430340, name: "Night's Cavalry", defeat_flag: 1039430340, region: "Liurnia - Liurnia Highway Far North", boss_type: BossType::Miniboss, runes: 5600, pos_x: -125.30, pos_y: 253.11, pos_z: -8.13, area_no: 60, block_no: 39, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1039440800, BossData { id: 1039440800, name: "Tibia Mariner", defeat_flag: 1039440800, region: "Liurnia - Divine Tower of Liurnia Entrance", boss_type: BossType::Miniboss, runes: 4700, pos_x: -81.59, pos_y: 294.79, pos_z: -41.36, area_no: 60, block_no: 39, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1039500800, BossData { id: 1039500800, name: "Godrick the Reskinned", defeat_flag: 1039500800, region: "Altus Plateau - Golden Lineage Evergaol", boss_type: BossType::Miniboss, runes: 26000, pos_x: -45.62, pos_y: 709.65, pos_z: -86.07, area_no: 60, block_no: 39, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1039540800, BossData { id: 1039540800, name: "Bell Bearing Hunter", defeat_flag: 1039540800, region: "Altus Plateau - Shaded Castle", boss_type: BossType::Miniboss, runes: 24000, pos_x: -53.72, pos_y: 768.29, pos_z: 56.51, area_no: 60, block_no: 39, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1040520800, BossData { id: 1040520800, name: "Black Knife Assassin", defeat_flag: 1040520800, region: "Altus Plateau - Sainted Hero's Grave Entrance", boss_type: BossType::Miniboss, runes: 10800, pos_x: 51.64, pos_y: 884.14, pos_z: 7.32, area_no: 60, block_no: 40, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1040530800, BossData { id: 1040530800, name: "Sanguine Noble", defeat_flag: 1040530800, region: "Altus Plateau - Writheblood Ruins", boss_type: BossType::Miniboss, runes: 8800, pos_x: -92.85, pos_y: 802.27, pos_z: 71.05, area_no: 60, block_no: 40, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1041500800, BossData { id: 1041500800, name: "Fallingstar Beast", defeat_flag: 1041500800, region: "Altus Plateau - South of Tree Sentinel Duo", boss_type: BossType::Miniboss, runes: 11000, pos_x: 42.84, pos_y: 834.24, pos_z: 109.24, area_no: 60, block_no: 41, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1041510800, BossData { id: 1041510800, name: "Tree Sentinel", defeat_flag: 1041510800, region: "Altus Plateau - Tree Sentinel Duo", boss_type: BossType::Miniboss, runes: 20000, pos_x: 91.09, pos_y: 851.27, pos_z: -31.35, area_no: 60, block_no: 41, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1041520800, BossData { id: 1041520800, name: "Ancient Dragon", defeat_flag: 1041520800, region: "Altus Plateau - Altus Tunnel Entrance", boss_type: BossType::Boss, runes: 60000, pos_x: 39.97, pos_y: 921.55, pos_z: -115.03, area_no: 60, block_no: 41, found_flag: 30020801, challenge_flag: 1041520300, mapgenie_id: None, });
    m.insert(1041530800, BossData { id: 1041530800, name: "Wormface", defeat_flag: 1041530800, region: "Altus Plateau - Minor Erdtree", boss_type: BossType::Miniboss, runes: 10000, pos_x: -77.48, pos_y: 785.14, pos_z: 29.23, area_no: 60, block_no: 41, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1042330800, BossData { id: 1042330800, name: "Ancient Hero of Zamor", defeat_flag: 1042330800, region: "Weeping Peninsula - Weeping Evergaol", boss_type: BossType::Miniboss, runes: 5400, pos_x: -126.39, pos_y: 19.91, pos_z: 108.76, area_no: 60, block_no: 42, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("165411"), });
    m.insert(1042360800, BossData { id: 1042360800, name: "Tree Sentinel", defeat_flag: 1042360800, region: "Limgrave - Church of Elleh", boss_type: BossType::Miniboss, runes: 3200, pos_x: -11.66, pos_y: 89.01, pos_z: 47.46, area_no: 60, block_no: 42, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("164444"), });
    m.insert(1042370800, BossData { id: 1042370800, name: "Crucible Knight", defeat_flag: 1042370800, region: "Limgrave - Stormhill Evergaol", boss_type: BossType::Miniboss, runes: 2100, pos_x: -83.61, pos_y: 160.59, pos_z: 65.00, area_no: 60, block_no: 42, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("164476"), });
    m.insert(1042380800, BossData { id: 1042380800, name: "Death Rite Bird", defeat_flag: 1042380800, region: "Stormhill - Stormgate", boss_type: BossType::Miniboss, runes: 2800, pos_x: 120.54, pos_y: 183.82, pos_z: 50.97, area_no: 60, block_no: 42, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("166201"), });
    m.insert(1042380850, BossData { id: 1042380850, name: "Bell Bearing Hunter", defeat_flag: 1042380850, region: "Stormhill - Warmaster's Shack", boss_type: BossType::Miniboss, runes: 2700, pos_x: 12.30, pos_y: 188.02, pos_z: 89.59, area_no: 60, block_no: 42, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("164004"), });
    m.insert(1042550800, BossData { id: 1042550800, name: "Godskin Apostle", defeat_flag: 1042550800, region: "Altus Plateau - Windmill Heights", boss_type: BossType::Miniboss, runes: 14000, pos_x: -35.55, pos_y: 968.22, pos_z: -38.97, area_no: 60, block_no: 42, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1043300800, BossData { id: 1043300800, name: "Leonine Misbegotten", defeat_flag: 1043300800, region: "Weeping Peninsula - Morne Moangrave", boss_type: BossType::Miniboss, runes: 3800, pos_x: -32.21, pos_y: 0.70, pos_z: -21.91, area_no: 60, block_no: 43, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("164812"), });
    m.insert(1043330800, BossData { id: 1043330800, name: "Erdtree Avatar", defeat_flag: 1043330800, region: "Weeping Peninsula - Minor Erdtree", boss_type: BossType::Miniboss, runes: 3600, pos_x: -55.40, pos_y: 83.11, pos_z: 21.96, area_no: 60, block_no: 43, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("165322"), });
    m.insert(1043360800, BossData { id: 1043360800, name: "Flying Dragon Agheel", defeat_flag: 1043360800, region: "Limgrave - Agheel Lake", boss_type: BossType::Miniboss, runes: 5000, pos_x: -95.50, pos_y: 64.96, pos_z: 80.23, area_no: 60, block_no: 43, found_flag: 30020801, challenge_flag: 1043360340, mapgenie_id: Some("164484"), });
    m.insert(1043370800, BossData { id: 1043370340, name: "Night's Cavalry", defeat_flag: 1043370800, region: "Limgrave - Agheel Lake North", boss_type: BossType::Miniboss, runes: 2400, pos_x: 72.46, pos_y: 90.96, pos_z: -94.70, area_no: 60, block_no: 43, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1043530800, BossData { id: 1044530800, name: "Bell Bearing Hunter", defeat_flag: 1043530800, region: "Capital Outskirts - Hermit Merchant's Shack", boss_type: BossType::Miniboss, runes: 29000, pos_x: -23.58, pos_y: 1025.94, pos_z: 75.99, area_no: 60, block_no: 44, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1044320800, BossData { id: 1044320340, name: "Death Rite Bird", defeat_flag: 1044320800, region: "Weeping Peninsula - Castle Morne Approach North", boss_type: BossType::Miniboss, runes: 3900, pos_x: -103.38, pos_y: 41.20, pos_z: 7.57, area_no: 60, block_no: 44, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1044320850, BossData { id: 1044320342, name: "Night's Cavalry", defeat_flag: 1044320850, region: "Weeping Peninsula - Castle Morne Approach North", boss_type: BossType::Miniboss, runes: 3400, pos_x: 36.61, pos_y: 42.82, pos_z: 102.45, area_no: 60, block_no: 44, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1044350800, BossData { id: 1044350800, name: "Bloodhound Knight Darriwil", defeat_flag: 1044350800, region: "Limgrave - Forlorn Hound Evergaol", boss_type: BossType::Miniboss, runes: 1900, pos_x: -17.40, pos_y: 105.68, pos_z: 119.83, area_no: 60, block_no: 44, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("164486"), });
    m.insert(1044360800, BossData { id: 1044360800, name: "Mad Pumpkin Head", defeat_flag: 1044360800, region: "Limgrave - Waypoint Ruins", boss_type: BossType::Miniboss, runes: 1100, pos_x: 17.39, pos_y: 80.81, pos_z: 29.78, area_no: 60, block_no: 44, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("164490"), });
    m.insert(1045390800, BossData { id: 1045390800, name: "Tibia Mariner", defeat_flag: 1045390800, region: "Limgrave - Summonwater Village", boss_type: BossType::Miniboss, runes: 2400, pos_x: -35.05, pos_y: 92.23, pos_z: 1.29, area_no: 60, block_no: 45, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("164859"), });
    m.insert(1045520800, BossData { id: 1045520800, name: "Draconic Tree Sentinel", defeat_flag: 1045520800, region: "Capital Outskirts - Capital Rampart", boss_type: BossType::Boss, runes: 50000, pos_x: 27.69, pos_y: 1023.82, pos_z: 43.92, area_no: 60, block_no: 45, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1047400800, BossData { id: 1047400800, name: "Putrid Avatar", defeat_flag: 1047400800, region: "Caelid - Minor Erdtree", boss_type: BossType::Miniboss, runes: 9600, pos_x: -102.34, pos_y: 126.24, pos_z: 102.54, area_no: 60, block_no: 47, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1048370800, BossData { id: 1048370800, name: "Decaying Ekzykes", defeat_flag: 1048370800, region: "Caelid - Caelid Highway South", boss_type: BossType::Boss, runes: 38000, pos_x: -48.09, pos_y: 114.95, pos_z: -42.67, area_no: 60, block_no: 48, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1048400800, BossData { id: 1048400800, name: "Mad Pumpkin Head", defeat_flag: 1048400800, region: "Caelid - Dragonbarrow West", boss_type: BossType::Miniboss, runes: 6300, pos_x: -118.79, pos_y: 138.42, pos_z: -91.28, area_no: 60, block_no: 48, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1048410800, BossData { id: 1048410800, name: "Bell Bearing Hunter", defeat_flag: 1048410800, region: "Greyoll's Dragonbarrow - Isolated Merchant's Shack", boss_type: BossType::Boss, runes: 50000, pos_x: -86.98, pos_y: 225.66, pos_z: -70.16, area_no: 60, block_no: 48, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1048510800, BossData { id: 1048510800, name: "Night's Cavalry", defeat_flag: 1048510800, region: "Mountaintops of the Giants - Forbidden Lands Midway", boss_type: BossType::Boss, runes: 36000, pos_x: -93.20, pos_y: 971.48, pos_z: 47.68, area_no: 60, block_no: 48, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1048570800, BossData { id: 1048570800, name: "Death Rite Bird", defeat_flag: 1048570800, region: "Consecrated Snowfield - Ordina, Liturgical Town", boss_type: BossType::GreatBoss, runes: 220000, pos_x: -106.89, pos_y: 1255.08, pos_z: 116.48, area_no: 60, block_no: 48, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1049370800, BossData { id: 1049370800, name: "Night's Cavalry", defeat_flag: 1049370800, region: "Caelid - Southern Aeonia Swamp Bank", boss_type: BossType::Miniboss, runes: 8500, pos_x: -116.52, pos_y: 102.11, pos_z: -7.90, area_no: 60, block_no: 49, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1049370850, BossData { id: 1049370850, name: "Death Rite Bird", defeat_flag: 1049370850, region: "Caelid - Southern Aeonia Swamp Bank", boss_type: BossType::Miniboss, runes: 15000, pos_x: 112.21, pos_y: 102.17, pos_z: 15.51, area_no: 60, block_no: 49, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1049380800, BossData { id: 1049380800, name: "Commander O'Neil", defeat_flag: 1049380800, region: "Caelid - East Aeonia Swamp", boss_type: BossType::Miniboss, runes: 12000, pos_x: -25.22, pos_y: 65.88, pos_z: 50.57, area_no: 60, block_no: 49, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("166073"), });
    m.insert(1049390800, BossData { id: 1049390800, name: "Nox Swordress & Nok Monk", defeat_flag: 1049390800, region: "Caelid - West Sellia", boss_type: BossType::Miniboss, runes: 6400, pos_x: 94.02, pos_y: 83.54, pos_z: 86.54, area_no: 60, block_no: 49, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1049390850, BossData { id: 1049390850, name: "Battlenage", defeat_flag: 1049390850, region: "Caelid - West Sellia", boss_type: BossType::Miniboss, runes: 7800, pos_x: -89.47, pos_y: 164.03, pos_z: -1.09, area_no: 60, block_no: 49, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1049520800, BossData { id: 1049520800, name: "Black Blade Kindred", defeat_flag: 1049520800, region: "Mountaintops of the Giants - Before Grand Lift of Rold", boss_type: BossType::Boss, runes: 60000, pos_x: -20.31, pos_y: 1048.49, pos_z: 54.71, area_no: 60, block_no: 49, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1050560800, BossData { id: 1050560800, name: "Great Wyrm Theodorix", defeat_flag: 1050560800, region: "Mountaintops of the Giants - Consecrated Snowfield", boss_type: BossType::GreatBoss, runes: 180000, pos_x: 15.43, pos_y: 1255.08, pos_z: 9.55, area_no: 60, block_no: 50, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1050570800, BossData { id: 1050570800, name: "Death Rite Bird", defeat_flag: 1050570800, region: "Mountaintops of the Giants - West of Castle Sol", boss_type: BossType::Boss, runes: 77000, pos_x: 64.60, pos_y: 1630.35, pos_z: -79.50, area_no: 60, block_no: 50, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1050570850, BossData { id: 1050570850, name: "Putrid Avatar", defeat_flag: 1050570850, region: "Mountaintops of the Giants - North of Minor Erdtree", boss_type: BossType::GreatBoss, runes: 160000, pos_x: -85.38, pos_y: 1390.24, pos_z: -56.42, area_no: 60, block_no: 50, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1051360800, BossData { id: 1051360800, name: "Crucible Knight", defeat_flag: 1051360800, region: "Caelid - Redmane Castle", boss_type: BossType::Miniboss, runes: 16000, pos_x: 78.39, pos_y: 91.78, pos_z: 37.64, area_no: 60, block_no: 51, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("166176"), });
    m.insert(1051400800, BossData { id: 1051400800, name: "Putrid Avatar", defeat_flag: 1051400800, region: "Greyoll's Dragonbarrow - Minor Erdtree", boss_type: BossType::Boss, runes: 91000, pos_x: 37.40, pos_y: 209.43, pos_z: 70.23, area_no: 60, block_no: 51, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1051430800, BossData { id: 1051430800, name: "Black Blade Kindred", defeat_flag: 1051430800, region: "Greyoll's Dragonbarrow - Bestial Sanctum", boss_type: BossType::Boss, runes: 88000, pos_x: 60.89, pos_y: 305.20, pos_z: -63.97, area_no: 60, block_no: 51, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1051570800, BossData { id: 1051570800, name: "Commander Niall", defeat_flag: 1051570800, region: "Mountaintops of the Giants - Castle Sol", boss_type: BossType::Boss, runes: 90000, pos_x: 78.08, pos_y: 1632.02, pos_z: 210.23, area_no: 60, block_no: 51, found_flag: 30020801, challenge_flag: 0, mapgenie_id: Some("167290"), });
    m.insert(1052410800, BossData { id: 1052410800, name: "Flying Dragon Greyll", defeat_flag: 1052410800, region: "Greyoll's Dragonbarrow - Southeast Farum Greatbridge", boss_type: BossType::Boss, runes: 80000, pos_x: -110.47, pos_y: 248.33, pos_z: 107.53, area_no: 60, block_no: 52, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1052410850, BossData { id: 1052410850, name: "Night's Cavalry", defeat_flag: 1052410850, region: "Greyoll's Dragonbarrow - Lenne's Rise", boss_type: BossType::Boss, runes: 42000, pos_x: 8.28, pos_y: 221.38, pos_z: 115.71, area_no: 60, block_no: 52, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1052520800, BossData { id: 1052520800, name: "Fire Giant", defeat_flag: 1052520800, region: "Southeast Mountaintops", boss_type: BossType::GreatBoss, runes: 180000, pos_x: 104.60, pos_y: 1859.69, pos_z: 58.67, area_no: 60, block_no: 52, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1052560800, BossData { id: 1052560800, name: "Erdtree Avatar", defeat_flag: 1052560800, region: "Mountaintops of the Giants - Minor Erdtree", boss_type: BossType::Boss, runes: 70000, pos_x: -58.98, pos_y: 1676.36, pos_z: 70.18, area_no: 60, block_no: 52, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1053560800, BossData { id: 1053560800, name: "Roundtable Knight Vyke", defeat_flag: 1053560800, region: "Mountaintops of the Giants - Lord Contender's Evergaol", boss_type: BossType::Boss, runes: 75000, pos_x: -52.50, pos_y: 1668.45, pos_z: -116.28, area_no: 60, block_no: 53, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    // NOT CORRECTED, deliberately. Like the two rows below this one carries a
    // "12" prefix that is outside the open-world tile grid, and area_no 60 +
    // the m60_48_55 entry in the game's openmap alloclist both point at
    // 1048550800. But unlike them its own `id` field agrees with the "12" form,
    // and the CE-era flag dump (`db/event_flags.rs`) lists 1248550800 as a real
    // flag — at an in-memory address far from the m60 tile region — while having
    // no 1048550800 at all. Two sources against two. It therefore reads Unknown,
    // which is the honest answer, rather than a guessed bit in a tile region.
    m.insert(1248550800, BossData { id: 1248550800, name: "Night's Cavalry", defeat_flag: 1248550800, region: "Southwest Mountaintops", boss_type: BossType::Boss, runes: 84000, pos_x: 108.17, pos_y: 1281.57, pos_z: -33.08, area_no: 60, block_no: 48, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    // CORRECTED 2026-07-20: both carried a "12" where the open-world tile prefix
    // is "10", so they addressed tiles outside the m60 grid and could never read
    // as defeated — Radahn among them. Each row contradicts itself (`id` and
    // `area_no: 60` both give the "10" form), the flag->map convention
    // 10AABBnnnn -> m60_AA_BB that every attributed pickup in the claims store
    // follows resolves them to m60_52_38 and m60_54_56, and the game's own
    // openmap eventflagalloclist allocates exactly those two tiles. Borealis has
    // a fourth: the CE-era dump lists 1054560800 and not 1254560800.
    m.insert(1052380800, BossData { id: 1052380800, name: "Starscourge Radahn", defeat_flag: 1052380800, region: "Southeast Caelid", boss_type: BossType::Demigod, runes: 70000, pos_x: -46.99, pos_y: 35.13, pos_z: -39.66, area_no: 60, block_no: 52, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(1054560800, BossData { id: 1054560800, name: "Borealis the Freezing Fog", defeat_flag: 1054560800, region: "Northeast Mountaintops", boss_type: BossType::GreatBoss, runes: 100000, pos_x: -124.93, pos_y: 1620.18, pos_z: 54.68, area_no: 60, block_no: 54, found_flag: 30020801, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2044450800, BossData { id: 2044450800, name: "Romina, Saint of the Bud", defeat_flag: 2044450800, region: "Ancient Ruins of Rauh", boss_type: BossType::GreatBoss, runes: 380000, pos_x: -61.24, pos_y: 625.31, pos_z: 110.57, area_no: 61, block_no: 44, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2044470800, BossData { id: 2044470800, name: "Rugalea the Great Red Bear", defeat_flag: 2044470800, region: "Ancient Ruins of Rauh", boss_type: BossType::GreatBoss, runes: 210000, pos_x: -52.12, pos_y: 321.72, pos_z: 112.28, area_no: 61, block_no: 44, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2045440800, BossData { id: 2045440800, name: "Ghostflame Dragon", defeat_flag: 2045440800, region: "Gravesite Plain", boss_type: BossType::GreatBoss, runes: 100000, pos_x: 59.10, pos_y: 256.42, pos_z: -73.89, area_no: 61, block_no: 45, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2046380800, BossData { id: 2046380800, name: "Dancer of Ranah", defeat_flag: 2046380800, region: "Cerulean Coast", boss_type: BossType::Boss, runes: 80000, pos_x: -24.90, pos_y: 9.25, pos_z: -96.83, area_no: 61, block_no: 46, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2046400800, BossData { id: 2046400800, name: "Demi-Human Queen Marigga", defeat_flag: 2046400800, region: "Cerulean Coast", boss_type: BossType::GreatBoss, runes: 100000, pos_x: -71.78, pos_y: 2.25, pos_z: -12.53, area_no: 61, block_no: 46, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2046410800, BossData { id: 2046410800, name: "Knight of the Solitary Gaol", defeat_flag: 2046410800, region: "Gravesite Plain", boss_type: BossType::Boss, runes: 70000, pos_x: -177.91, pos_y: 317.66, pos_z: 54.75, area_no: 61, block_no: 46, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2046450800, BossData { id: 2046450800, name: "Red Bear", defeat_flag: 2046450800, region: "Gravesite Plain", boss_type: BossType::Boss, runes: 80000, pos_x: 109.20, pos_y: 395.92, pos_z: -80.75, area_no: 61, block_no: 46, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2046460800, BossData { id: 2046460800, name: "Divine Beast Dancing Lion", defeat_flag: 2046460800, region: "Gravesite Plain", boss_type: BossType::GreatBoss, runes: 180000, pos_x: -62.72, pos_y: 536.00, pos_z: -40.75, area_no: 61, block_no: 46, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2047390800, BossData { id: 2047390800, name: "Death Rite Bird", defeat_flag: 2047390800, region: "Cerulean Coast", boss_type: BossType::GreatBoss, runes: 230000, pos_x: 93.02, pos_y: 84.98, pos_z: 55.78, area_no: 61, block_no: 47, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2047450800, BossData { id: 2047450800, name: "Black Knight Garrew", defeat_flag: 2047450800, region: "Scadu Altus", boss_type: BossType::Boss, runes: 80000, pos_x: -27.67, pos_y: 346.02, pos_z: 117.34, area_no: 61, block_no: 47, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2048380850, BossData { id: 2048380850, name: "Ghostflame Dragon", defeat_flag: 2048380850, region: "Cerulean Coast", boss_type: BossType::GreatBoss, runes: 120000, pos_x: -90.03, pos_y: 32.28, pos_z: -91.60, area_no: 61, block_no: 48, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2048440800, BossData { id: 2048440800, name: "Rellana, Twin Moon Knight", defeat_flag: 2048440800, region: "Gravesite Plain", boss_type: BossType::GreatBoss, runes: 240000, pos_x: -55.49, pos_y: 427.01, pos_z: 50.56, area_no: 61, block_no: 48, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2049410800, BossData { id: 2049410800, name: "Jagged Peak Drake (Solo)", defeat_flag: 2049410800, region: "Jagged Peak", boss_type: BossType::Boss, runes: 90000, pos_x: 80.59, pos_y: 65.82, pos_z: -106.26, area_no: 61, block_no: 49, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2049430800, BossData { id: 2049430800, name: "Ghostflame Dragon", defeat_flag: 2049430800, region: "Moorth Highway", boss_type: BossType::GreatBoss, runes: 120000, pos_x: -8.79, pos_y: 379.01, pos_z: 116.91, area_no: 61, block_no: 49, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2049430850, BossData { id: 2049430850, name: "Black Knight Edredd", defeat_flag: 2049430850, region: "Scadu Altus", boss_type: BossType::Boss, runes: 80000, pos_x: 68.88, pos_y: 396.48, pos_z: -95.66, area_no: 61, block_no: 49, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2049450800, BossData { id: 2049450800, name: "Ralva the Great Red Bear", defeat_flag: 2049450800, region: "Scadu Altus", boss_type: BossType::GreatBoss, runes: 180000, pos_x: 62.85, pos_y: 396.02, pos_z: 123.83, area_no: 61, block_no: 49, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2049480800, BossData { id: 2049480800, name: "Commander Gaius", defeat_flag: 2049480800, region: "Scadu Altus", boss_type: BossType::GreatBoss, runes: 230000, pos_x: 80.91, pos_y: 580.04, pos_z: 6.88, area_no: 61, block_no: 49, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2050470800, BossData { id: 2050470800, name: "Tree Sentinel , Torch", defeat_flag: 2050470800, region: "Hinterland", boss_type: BossType::GreatBoss, runes: 120000, pos_x: 14.86, pos_y: 559.44, pos_z: 106.53, area_no: 61, block_no: 50, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2050480800, BossData { id: 2050480800, name: "Scadutree Avatar", defeat_flag: 2050480800, region: "Scaduview", boss_type: BossType::GreatBoss, runes: 260000, pos_x: -50.68, pos_y: 190.02, pos_z: 86.67, area_no: 61, block_no: 50, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2050480860, BossData { id: 2050480860, name: "Tree Sentinel", defeat_flag: 2050480860, region: "Hinterland", boss_type: BossType::GreatBoss, runes: 120000, pos_x: 47.62, pos_y: 541.52, pos_z: -63.28, area_no: 61, block_no: 50, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2051440800, BossData { id: 2051440800, name: "Rakshasa", defeat_flag: 2051440800, region: "Scadu Altus", boss_type: BossType::Boss, runes: 90000, pos_x: 5.08, pos_y: 162.59, pos_z: 94.24, area_no: 61, block_no: 51, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2052400800, BossData { id: 2052400800, name: "Jagged Peak Drake (Duo)", defeat_flag: 2052400800, region: "Jagged Peak", boss_type: BossType::GreatBoss, runes: 120000, pos_x: -69.75, pos_y: 287.39, pos_z: -77.82, area_no: 61, block_no: 52, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2052430800, BossData { id: 2052430800, name: "Jori, the Elder Inquisitor", defeat_flag: 2052430800, region: "Abyssal Woods", boss_type: BossType::GreatBoss, runes: 260000, pos_x: -68.10, pos_y: -512.16, pos_z: 67.91, area_no: 61, block_no: 52, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2052480800, BossData { id: 2052480800, name: "Fallingstar Beast", defeat_flag: 2052480800, region: "Finger Ruins", boss_type: BossType::GreatBoss, runes: 170000, pos_x: 39.21, pos_y: 478.32, pos_z: 117.00, area_no: 61, block_no: 52, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2054390800, BossData { id: 2054390800, name: "Bayle the Dread", defeat_flag: 2054390800, region: "Jagged Peak", boss_type: BossType::GreatBoss, runes: 490000, pos_x: 112.04, pos_y: 953.86, pos_z: 26.01, area_no: 61, block_no: 54, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m.insert(2054390850, BossData { id: 2054390850, name: "Ancient Dragon Senessax", defeat_flag: 2054390850, region: "Jagged Peak", boss_type: BossType::GreatBoss, runes: 200000, pos_x: -72.88, pos_y: 511.96, pos_z: 19.44, area_no: 61, block_no: 54, found_flag: 0, challenge_flag: 0, mapgenie_id: None, });
    m
});

/// All unique regions with bosses
pub static BOSS_REGIONS: &[&str] = &[
    "Abandoned Cave",
    "Abyssal Woods",
    "Academy Crystal Cave",
    "Academy of Raya Lucaria",
    "Ainsel River",
    "Altus Plateau - Abandoned Coffin",
    "Altus Plateau - Altus Tunnel Entrance",
    "Altus Plateau - Erdtree-Gazing Hill- Lux Ruins",
    "Altus Plateau - Golden Lineage Evergaol",
    "Altus Plateau - Minor Erdtree",
    "Altus Plateau - Sainted Hero's Grave Entrance",
    "Altus Plateau - Shaded Castle",
    "Altus Plateau - South of Tree Sentinel Duo",
    "Altus Plateau - Tree Sentinel Duo",
    "Altus Plateau - Windmill Heights",
    "Altus Plateau - Writheblood Ruins",
    "Altus Plateau - Wyndham Ruins",
    "Altus Tunnel",
    "Ancient Ruins of Rauh",
    "Auriza Hero's Grave",
    "Auriza Side Tomb",
    "Bellum Highway - East Raya Lucaria Gate",
    "Bellum Highway - Minor Erdtree",
    "Belurat Gaol",
    "Belurat, Tower Settlement",
    "Black Knife Catacombs",
    "Bonny Gaol",
    "Caelid - Caelid Highway South",
    "Caelid - Dragonbarrow West",
    "Caelid - East Aeonia Swamp",
    "Caelid - Minor Erdtree",
    "Caelid - Redmane Castle",
    "Caelid - Southern Aeonia Swamp Bank",
    "Caelid - West Sellia",
    "Caelid Catacombs",
    "Capital Outskirts - Capital Rampart",
    "Capital Outskirts - Hermit Merchant's Shack",
    "Cave of the Forlorn",
    "Cerulean Coast",
    "Chapel of Anticipation",
    "Cliffbottom Catacombs",
    "Coastal Cave",
    "Consecrated Snowfield - Ordina, Liturgical Town",
    "Consecrated Snowfield Catacombs",
    "Crumbling Farum Azula",
    "Deathtouched Catacombs",
    "Deeproot Depths",
    "Divine Tower of Caelid",
    "Divine Tower of East Altus",
    "Divine Tower of West Altus",
    "Dragon's Pit",
    "Dragonbarrow Cave",
    "Earthbore Cave",
    "Enir-Ilim",
    "Finger Birthing Grounds",
    "Finger Ruins",
    "Fog Rift Catacombs",
    "Gael Tunnel",
    "Gaol Cave",
    "Gelmir Hero's Grave",
    "Giant-Conquering Hero's Grave",
    "Giants' Mountaintop Catacombs",
    "Gravesite Plain",
    "Greyoll's Dragonbarrow - Bestial Sanctum",
    "Greyoll's Dragonbarrow - Isolated Merchant's Shack",
    "Greyoll's Dragonbarrow - Lenne's Rise",
    "Greyoll's Dragonbarrow - Minor Erdtree",
    "Greyoll's Dragonbarrow - Southeast Farum Greatbridge",
    "Groveside Cave",
    "Hidden Path to the Haligtree",
    "Highroad Cave",
    "Hinterland",
    "Impaler's Catacombs",
    "Jagged Peak",
    "Lakeside Crystal Cave",
    "Lamenter's Gaol",
    "Leyndell Ashen Capital",
    "Leyndell- Royal Capital",
    "Limgrave - Agheel Lake",
    "Limgrave - Agheel Lake North",
    "Limgrave - Church of Elleh",
    "Limgrave - Forlorn Hound Evergaol",
    "Limgrave - Stormhill Evergaol",
    "Limgrave - Summonwater Village",
    "Limgrave - Waypoint Ruins",
    "Limgrave Tunnels",
    "Liurnia - Albinauric Village",
    "Liurnia - Caria Manor",
    "Liurnia - Church of Vows",
    "Liurnia - Cuckoo's Evergaol",
    "Liurnia - Divine Tower of Liurnia Entrance",
    "Liurnia - Gate Town Northwest",
    "Liurnia - Kingsrealm Ruins",
    "Liurnia - Laskyar Ruins",
    "Liurnia - Liurnia Highway Far North",
    "Liurnia - Malefactor's Evergaol",
    "Liurnia - Meeting Place",
    "Liurnia - Minor Erdtree",
    "Liurnia - Moonfolk Ruins",
    "Liurnia - Moonlight Altar",
    "Liurnia - Ranni's Rise",
    "Liurnia - Royal Grave Evergaol",
    "Midra's Manse",
    "Minor Erdtree Catacombs",
    "Miquella's Haligtree",
    "Mohgwyn Palace",
    "Moorth Highway",
    "Morne Tunnel",
    "Mountaintops of the Giants - Before Grand Lift of Rold",
    "Mountaintops of the Giants - Castle Sol",
    "Mountaintops of the Giants - Consecrated Snowfield",
    "Mountaintops of the Giants - Forbidden Lands Midway",
    "Mountaintops of the Giants - Lord Contender's Evergaol",
    "Mountaintops of the Giants - Minor Erdtree",
    "Mountaintops of the Giants - North of Minor Erdtree",
    "Mountaintops of the Giants - West of Castle Sol",
    "Mt. Gelmir - Minor Erdtree",
    "Mt. Gelmir - Ninth Mt. Gelmir Campsite",
    "Mt. Gelmir - Primeval Sorcerer Azur",
    "Mt. Gelmir - Seethewater Terminus",
    "Murkwater Catacombs",
    "Murkwater Cave",
    "Nokron Eternal City",
    "Northeast Mountaintops",
    "Old Altus Tunnel",
    "Perfumer's Grotto",
    "Raya Lucaria Crystal Tunnel",
    "Rivermouth Cave",
    "Road's End Catacombs",
    "Ruin-Strewn Precipice",
    "Sage's Cave",
    "Sainted Hero's Grave",
    "Scadu Altus",
    "Scaduview",
    "Scorpion River Catacombs",
    "Seethewater Cave",
    "Sellia Crystal Tunnel",
    "Sellia Hideaway",
    "Shadow Keep",
    "Siofra River",
    "Southeast Caelid",
    "Southeast Mountaintops",
    "Southwest Mountaintops",
    "Specimen Storehouse",
    "Spiritcaller's Cave",
    "Stillwater Cave",
    "Stone Coffin Fissure",
    "Stone Platform",
    "Stormfoot Catacombs",
    "Stormhill - Stormgate",
    "Stormhill - Warmaster's Shack",
    "Stormveil Castle",
    "Stranded Graveyard",
    "Subterranean Shunning-Grounds",
    "Tombsward Catacombs",
    "Tombsward Cave",
    "Unsightly Catacombs",
    "Volcano Cave",
    "Volcano Manor",
    "War-Dead Catacombs",
    "Weeping Peninsula - Castle Morne Approach North",
    "Weeping Peninsula - Minor Erdtree",
    "Weeping Peninsula - Morne Moangrave",
    "Weeping Peninsula - Weeping Evergaol",
    "Wyndham Catacombs",
    "Yelough Anix Tunnel",
];
