//! Bosses database with defeat flags
//! This file is auto-generated by scripts/generate_db.py - do not edit manually

use once_cell::sync::Lazy;
use std::collections::HashMap;

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum BossType {
    Demigod,
    GreatBoss,
    Boss,
    Miniboss,
    Unknown,
}

impl BossType {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Demigod => "Demigod",
            Self::GreatBoss => "Great Boss",
            Self::Boss => "Boss",
            Self::Miniboss => "Miniboss",
            Self::Unknown => "Unknown",
        }
    }
}

#[derive(Debug, Clone)]
pub struct BossData {
    pub id: u32,
    pub name: &'static str,
    pub defeat_flag: u32,
    pub region: &'static str,
    pub boss_type: BossType,
    // Enrichment
    pub mapgenie_id: Option<&'static str>,
}

/// Bosses database (17 entries)
pub static BOSSES_DATA: Lazy<HashMap<u32, BossData>> = Lazy::new(|| {
    let mut m = HashMap::new();
    m.insert(10000800, BossData { id: 10000800, name: "Godrick the Grafted", defeat_flag: 10000800, region: "Stormveil Castle", boss_type: BossType::Demigod, mapgenie_id: Some("164421"), });
    m.insert(14000800, BossData { id: 14000800, name: "Rennala, Queen of the Full Moon", defeat_flag: 14000800, region: "Academy of Raya Lucaria", boss_type: BossType::Demigod, mapgenie_id: Some("164430"), });
    m.insert(16000800, BossData { id: 16000800, name: "Rykard, Lord of Blasphemy", defeat_flag: 16000800, region: "Volcano Manor", boss_type: BossType::Demigod, mapgenie_id: Some("167571"), });
    m.insert(12010800, BossData { id: 12010800, name: "Starscourge Radahn", defeat_flag: 12010800, region: "Caelid", boss_type: BossType::Demigod, mapgenie_id: None, });
    m.insert(15000800, BossData { id: 15000800, name: "Malenia, Blade of Miquella", defeat_flag: 15000800, region: "Haligtree", boss_type: BossType::Demigod, mapgenie_id: Some("176825"), });
    m.insert(12050800, BossData { id: 12050800, name: "Mohg, Lord of Blood", defeat_flag: 12050800, region: "Mohgwyn Palace", boss_type: BossType::Demigod, mapgenie_id: Some("169764"), });
    m.insert(11000800, BossData { id: 11000800, name: "Morgott, the Omen King", defeat_flag: 11000800, region: "Leyndell", boss_type: BossType::Demigod, mapgenie_id: Some("176808"), });
    m.insert(13000800, BossData { id: 13000800, name: "Maliketh, the Black Blade", defeat_flag: 13000800, region: "Crumbling Farum Azula", boss_type: BossType::GreatBoss, mapgenie_id: Some("169007"), });
    m.insert(19000800, BossData { id: 19000800, name: "Radagon / Elden Beast", defeat_flag: 19000800, region: "Stone Platform", boss_type: BossType::GreatBoss, mapgenie_id: None, });
    m.insert(16000850, BossData { id: 16000850, name: "God-Devouring Serpent", defeat_flag: 16000850, region: "Volcano Manor", boss_type: BossType::GreatBoss, mapgenie_id: Some("168177"), });
    m.insert(11050800, BossData { id: 11050800, name: "Hoarah Loux, Warrior", defeat_flag: 11050800, region: "Leyndell", boss_type: BossType::GreatBoss, mapgenie_id: None, });
    m.insert(1035420800, BossData { id: 1035420800, name: "Margit, the Fell Omen", defeat_flag: 1035420800, region: "Stormhill", boss_type: BossType::Boss, mapgenie_id: None, });
    m.insert(1042380800, BossData { id: 1042380800, name: "Tree Sentinel", defeat_flag: 1042380800, region: "Limgrave", boss_type: BossType::Boss, mapgenie_id: Some("166201"), });
    m.insert(1044350800, BossData { id: 1044350800, name: "Flying Dragon Agheel", defeat_flag: 1044350800, region: "Limgrave", boss_type: BossType::Boss, mapgenie_id: Some("164486"), });
    m.insert(1034500800, BossData { id: 1034500800, name: "Tibia Mariner", defeat_flag: 1034500800, region: "Limgrave", boss_type: BossType::Boss, mapgenie_id: None, });
    m.insert(1035500800, BossData { id: 1035500800, name: "Bell Bearing Hunter", defeat_flag: 1035500800, region: "Limgrave", boss_type: BossType::Boss, mapgenie_id: Some("165490"), });
    m.insert(1036540800, BossData { id: 1036540800, name: "Night's Cavalry", defeat_flag: 1036540800, region: "Limgrave", boss_type: BossType::Boss, mapgenie_id: None, });
    m
});

/// All unique regions with bosses
pub static BOSS_REGIONS: &[&str] = &[
    "Academy of Raya Lucaria",
    "Caelid",
    "Crumbling Farum Azula",
    "Haligtree",
    "Leyndell",
    "Limgrave",
    "Mohgwyn Palace",
    "Stone Platform",
    "Stormhill",
    "Stormveil Castle",
    "Volcano Manor",
];
