//! Entity relationship data generated from boss_drops.json + GameAreaParam proximity
//! Originally generated by the removed Python lab (scripts/generate_db.py; see docs/archive/PYTHON-LAB.md) — now maintained in-tree; regenerate from primary sources per docs/DATA-SOURCES.md.

use once_cell::sync::Lazy;
use std::collections::HashMap;

/// Drop category for boss rewards
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DropCategory {
    Remembrance,
    GreatRune,
    Weapon,
    AshOfWar,
    Talisman,
    SpiritAsh,
    KeyItem,
    Incantation,
    Sorcery,
    Other,
}

impl DropCategory {
    pub fn display_name(&self) -> &'static str {
        match self {
            DropCategory::Remembrance => "Remembrance",
            DropCategory::GreatRune => "Great Rune",
            DropCategory::Weapon => "Weapon",
            DropCategory::AshOfWar => "Ash of War",
            DropCategory::Talisman => "Talisman",
            DropCategory::SpiritAsh => "Spirit Ash",
            DropCategory::KeyItem => "Key Item",
            DropCategory::Incantation => "Incantation",
            DropCategory::Sorcery => "Sorcery",
            DropCategory::Other => "Other",
        }
    }
}

/// A boss drop entry
#[derive(Debug, Clone)]
pub struct BossDropEntry {
    pub boss_flag: u32,
    pub boss_name: &'static str,
    pub item_id: u32,
    pub item_name: &'static str,
    pub category: DropCategory,
}

/// All boss drops (62 entries)
pub static BOSS_DROPS: &[BossDropEntry] = &[
    BossDropEntry { boss_flag: 10000800, boss_name: "Godrick the Grafted", item_id: 8150, item_name: "Remembrance of the Grafted", category: DropCategory::Remembrance },
    BossDropEntry { boss_flag: 10000800, boss_name: "Godrick the Grafted", item_id: 8101, item_name: "Godrick's Great Rune", category: DropCategory::GreatRune },
    BossDropEntry { boss_flag: 14000800, boss_name: "Rennala Queen of the Full Moon", item_id: 8151, item_name: "Remembrance of the Full Moon Queen", category: DropCategory::Remembrance },
    BossDropEntry { boss_flag: 14000800, boss_name: "Rennala Queen of the Full Moon", item_id: 8103, item_name: "Great Rune of the Unborn", category: DropCategory::GreatRune },
    BossDropEntry { boss_flag: 1052380800, boss_name: "Starscourge Radahn", item_id: 8153, item_name: "Remembrance of the Starscourge", category: DropCategory::Remembrance },
    BossDropEntry { boss_flag: 1052380800, boss_name: "Starscourge Radahn", item_id: 8105, item_name: "Radahn's Great Rune", category: DropCategory::GreatRune },
    BossDropEntry { boss_flag: 16000800, boss_name: "Rykard Lord of Blasphemy", item_id: 8152, item_name: "Remembrance of the Blasphemous", category: DropCategory::Remembrance },
    BossDropEntry { boss_flag: 16000800, boss_name: "Rykard Lord of Blasphemy", item_id: 8104, item_name: "Rykard's Great Rune", category: DropCategory::GreatRune },
    BossDropEntry { boss_flag: 11000800, boss_name: "Morgott, the Omen King", item_id: 8156, item_name: "Remembrance of the Omen King", category: DropCategory::Remembrance },
    BossDropEntry { boss_flag: 11000800, boss_name: "Morgott, the Omen King", item_id: 8102, item_name: "Morgott's Great Rune", category: DropCategory::GreatRune },
    BossDropEntry { boss_flag: 12050800, boss_name: "Mohg Lord of Blood", item_id: 8155, item_name: "Remembrance of the Blood Lord", category: DropCategory::Remembrance },
    BossDropEntry { boss_flag: 12050800, boss_name: "Mohg Lord of Blood", item_id: 8107, item_name: "Mohg's Great Rune", category: DropCategory::GreatRune },
    BossDropEntry { boss_flag: 15000800, boss_name: "Malenia Blade of Miquella", item_id: 8154, item_name: "Remembrance of the Rot Goddess", category: DropCategory::Remembrance },
    BossDropEntry { boss_flag: 15000800, boss_name: "Malenia Blade of Miquella", item_id: 8106, item_name: "Malenia's Great Rune", category: DropCategory::GreatRune },
    BossDropEntry { boss_flag: 13000800, boss_name: "Maliketh, the Black Blade", item_id: 8157, item_name: "Remembrance of the Black Blade", category: DropCategory::Remembrance },
    BossDropEntry { boss_flag: 11050800, boss_name: "Hoarah Loux", item_id: 8159, item_name: "Remembrance of Hoarah Loux", category: DropCategory::Remembrance },
    BossDropEntry { boss_flag: 19000800, boss_name: "Elden Beast", item_id: 8158, item_name: "Elden Remembrance", category: DropCategory::Remembrance },
    BossDropEntry { boss_flag: 1052520800, boss_name: "Fire Giant", item_id: 8164, item_name: "Remembrance of the Fire Giant", category: DropCategory::Remembrance },
    BossDropEntry { boss_flag: 13000830, boss_name: "Dragonlord Placidusax", item_id: 8161, item_name: "Remembrance of the Dragonlord", category: DropCategory::Remembrance },
    BossDropEntry { boss_flag: 12030850, boss_name: "Lichdragon Fortissax", item_id: 8162, item_name: "Remembrance of the Lichdragon", category: DropCategory::Remembrance },
    BossDropEntry { boss_flag: 12040800, boss_name: "Astel Naturalborn of the Void", item_id: 8165, item_name: "Remembrance of the Naturalborn", category: DropCategory::Remembrance },
    BossDropEntry { boss_flag: 12090800, boss_name: "Regal Ancestor Spirit", item_id: 8163, item_name: "Remembrance of the Regal Ancestor", category: DropCategory::Remembrance },
    BossDropEntry { boss_flag: 1043300800, boss_name: "Leonine Misbegotten", item_id: 21100000, item_name: "Grafted Blade Greatsword", category: DropCategory::Weapon },
    BossDropEntry { boss_flag: 1044360800, boss_name: "Mad Pumpkin Head", item_id: 17020000, item_name: "Bloodhound's Fang", category: DropCategory::Weapon },
    BossDropEntry { boss_flag: 1042380850, boss_name: "Bell Bearing Hunter", item_id: 15110000, item_name: "Golden Halberd", category: DropCategory::Weapon },
    BossDropEntry { boss_flag: 30000800, boss_name: "Cemetery Shade", item_id: 9000000, item_name: "Battle Hammer", category: DropCategory::Weapon },
    BossDropEntry { boss_flag: 32010800, boss_name: "Stonedigger Troll", item_id: 17170000, item_name: "Rusted Anchor", category: DropCategory::Weapon },
    BossDropEntry { boss_flag: 1037530800, boss_name: "Demi-Human Queen Maggie", item_id: 21150000, item_name: "Fallingstar Beast Jaw", category: DropCategory::Weapon },
    BossDropEntry { boss_flag: 1049380800, boss_name: "Commander O'Neil", item_id: 15140000, item_name: "Commander's Standard", category: DropCategory::Weapon },
    BossDropEntry { boss_flag: 12020800, boss_name: "Valiant Gargoyles", item_id: 12040000, item_name: "Gargoyle's Greatsword", category: DropCategory::Weapon },
    BossDropEntry { boss_flag: 12020800, boss_name: "Valiant Gargoyles", item_id: 12060000, item_name: "Gargoyle's Twinblade", category: DropCategory::Weapon },
    BossDropEntry { boss_flag: 39200800, boss_name: "Magma Wyrm Makar", item_id: 21040000, item_name: "Magma Wyrm's Scalesword", category: DropCategory::Weapon },
    BossDropEntry { boss_flag: 14000850, boss_name: "Red Wolf of Radagon", item_id: 8010, item_name: "Memory Stone", category: DropCategory::KeyItem },
    BossDropEntry { boss_flag: 1044350800, boss_name: "Bloodhound Knight Darriwil", item_id: 8000, item_name: "Dragon Heart", category: DropCategory::KeyItem },
    BossDropEntry { boss_flag: 1034450800, boss_name: "Glintstone Dragon Smarag", item_id: 8000, item_name: "Dragon Heart", category: DropCategory::KeyItem },
    BossDropEntry { boss_flag: 1048370800, boss_name: "Decaying Ekzykes", item_id: 8000, item_name: "Dragon Heart", category: DropCategory::KeyItem },
    BossDropEntry { boss_flag: 11000850, boss_name: "Godfrey, First Elden Lord", item_id: 8011, item_name: "Talisman Pouch", category: DropCategory::KeyItem },
    BossDropEntry { boss_flag: 1051560800, boss_name: "Unknown Boss (1051560800)", item_id: 1350, item_name: "Veteran's Prosthesis", category: DropCategory::Weapon },
    BossDropEntry { boss_flag: 12020850, boss_name: "Mimic Tear", item_id: 1980, item_name: "Larval Tear", category: DropCategory::KeyItem },
    BossDropEntry { boss_flag: 12080800, boss_name: "Ancestor Spirit", item_id: 1080, item_name: "Ancestral Spirit's Horn", category: DropCategory::Talisman },
    BossDropEntry { boss_flag: 12080800, boss_name: "Ancestor Spirit", item_id: 419000, item_name: "Ancestral Follower Ashes", category: DropCategory::SpiritAsh },
    BossDropEntry { boss_flag: 1042330800, boss_name: "Ancient Hero of Zamor", item_id: 1020, item_name: "Radagon's Scarseal", category: DropCategory::Talisman },
    BossDropEntry { boss_flag: 31190800, boss_name: "Black Knife Assassin", item_id: 1200, item_name: "Godskin Swaddling Cloth", category: DropCategory::Talisman },
    BossDropEntry { boss_flag: 1042380800, boss_name: "Death Rite Bird", item_id: 4040, item_name: "Aspects of the Crucible: Tail", category: DropCategory::Incantation },
    BossDropEntry { boss_flag: 30070800, boss_name: "Erdtree Burial Watchdog", item_id: 310200, item_name: "Ordovis's Vortex", category: DropCategory::Incantation },
    BossDropEntry { boss_flag: 1035500800, boss_name: "Loretta, Royal Knight", item_id: 4003, item_name: "Loretta's Greatbow", category: DropCategory::Sorcery },
    BossDropEntry { boss_flag: 35000800, boss_name: "Mohg The Omen", item_id: 4370, item_name: "Bloodflame Talons", category: DropCategory::Incantation },
    BossDropEntry { boss_flag: 30030800, boss_name: "Spirit-Caller Snail", item_id: 410000, item_name: "Lhutel the Headless", category: DropCategory::SpiritAsh },
    BossDropEntry { boss_flag: 1050570800, boss_name: "Death Rite Bird", item_id: 424000, item_name: "Black Knife Tiche", category: DropCategory::SpiritAsh },
    BossDropEntry { boss_flag: 30190800, boss_name: "Putrid Grave Warden Duelist", item_id: 417000, item_name: "Ancient Dragon Knight Kristoff", category: DropCategory::SpiritAsh },
    BossDropEntry { boss_flag: 1042370800, boss_name: "Crucible Knight", item_id: 22000200, item_name: "Ash of War: Repeating Thrust", category: DropCategory::AshOfWar },
    BossDropEntry { boss_flag: 1048380800, boss_name: "Unknown Boss (1048380800)", item_id: 22000400, item_name: "Ash of War: Poison Moth Flight", category: DropCategory::AshOfWar },
    BossDropEntry { boss_flag: 1037500800, boss_name: "Unknown Boss (1037500800)", item_id: 22000800, item_name: "Ash of War: Ice Spear", category: DropCategory::AshOfWar },
    BossDropEntry { boss_flag: 1040510800, boss_name: "Unknown Boss (1040510800)", item_id: 22001400, item_name: "Ash of War: Shared Order", category: DropCategory::AshOfWar },
    BossDropEntry { boss_flag: 13000850, boss_name: "Godskin Duo", item_id: 8700, item_name: "Smithing-Stone Miner's Bell Bearing [4]", category: DropCategory::KeyItem },
    BossDropEntry { boss_flag: 16000850, boss_name: "Godskin Noble", item_id: 8010, item_name: "Memory Stone", category: DropCategory::KeyItem },
    BossDropEntry { boss_flag: 15010800, boss_name: "Unknown Boss (15010800)", item_id: 429000, item_name: "Cleanrot Knight Finlay", category: DropCategory::SpiritAsh },
    BossDropEntry { boss_flag: 20000800, boss_name: "Divine Beast Dancing Lion", item_id: 8180, item_name: "Remembrance of the Dancing Lion", category: DropCategory::Remembrance },
    BossDropEntry { boss_flag: 21010800, boss_name: "Messmer the Impaler", item_id: 8181, item_name: "Remembrance of the Impaler", category: DropCategory::Remembrance },
    BossDropEntry { boss_flag: 20010800, boss_name: "Promised Consort Radahn", item_id: 8184, item_name: "Remembrance of a God and a Lord", category: DropCategory::Remembrance },
    BossDropEntry { boss_flag: 28000800, boss_name: "Midra, Lord of Frenzied Flame", item_id: 8183, item_name: "Remembrance of the Lord of Frenzied Flame", category: DropCategory::Remembrance },
    BossDropEntry { boss_flag: 25000800, boss_name: "Metyr, Mother of Fingers", item_id: 8185, item_name: "Remembrance of the Mother of Fingers", category: DropCategory::Remembrance },
];

/// Item -> bosses that drop it (59 items)
pub static ITEM_DROPPED_BY: Lazy<HashMap<u32, Vec<(u32, &'static str)>>> = Lazy::new(|| {
    let mut m = HashMap::new();
    m.insert(1020, vec![(1042330800, "Ancient Hero of Zamor")]);
    m.insert(1080, vec![(12080800, "Ancestor Spirit")]);
    m.insert(1200, vec![(31190800, "Black Knife Assassin")]);
    m.insert(1350, vec![(1051560800, "Unknown Boss (1051560800)")]);
    m.insert(1980, vec![(12020850, "Mimic Tear")]);
    m.insert(4003, vec![(1035500800, "Loretta, Royal Knight")]);
    m.insert(4040, vec![(1042380800, "Death Rite Bird")]);
    m.insert(4370, vec![(35000800, "Mohg The Omen")]);
    m.insert(8000, vec![(1044350800, "Bloodhound Knight Darriwil"), (1034450800, "Glintstone Dragon Smarag"), (1048370800, "Decaying Ekzykes")]);
    m.insert(8010, vec![(14000850, "Red Wolf of Radagon"), (16000850, "Godskin Noble")]);
    m.insert(8011, vec![(11000850, "Godfrey, First Elden Lord")]);
    m.insert(8101, vec![(10000800, "Godrick the Grafted")]);
    m.insert(8102, vec![(11000800, "Morgott, the Omen King")]);
    m.insert(8103, vec![(14000800, "Rennala Queen of the Full Moon")]);
    m.insert(8104, vec![(16000800, "Rykard Lord of Blasphemy")]);
    m.insert(8105, vec![(1052380800, "Starscourge Radahn")]);
    m.insert(8106, vec![(15000800, "Malenia Blade of Miquella")]);
    m.insert(8107, vec![(12050800, "Mohg Lord of Blood")]);
    m.insert(8150, vec![(10000800, "Godrick the Grafted")]);
    m.insert(8151, vec![(14000800, "Rennala Queen of the Full Moon")]);
    m.insert(8152, vec![(16000800, "Rykard Lord of Blasphemy")]);
    m.insert(8153, vec![(1052380800, "Starscourge Radahn")]);
    m.insert(8154, vec![(15000800, "Malenia Blade of Miquella")]);
    m.insert(8155, vec![(12050800, "Mohg Lord of Blood")]);
    m.insert(8156, vec![(11000800, "Morgott, the Omen King")]);
    m.insert(8157, vec![(13000800, "Maliketh, the Black Blade")]);
    m.insert(8158, vec![(19000800, "Elden Beast")]);
    m.insert(8159, vec![(11050800, "Hoarah Loux")]);
    m.insert(8161, vec![(13000830, "Dragonlord Placidusax")]);
    m.insert(8162, vec![(12030850, "Lichdragon Fortissax")]);
    m.insert(8163, vec![(12090800, "Regal Ancestor Spirit")]);
    m.insert(8164, vec![(1052520800, "Fire Giant")]);
    m.insert(8165, vec![(12040800, "Astel Naturalborn of the Void")]);
    m.insert(8180, vec![(20000800, "Divine Beast Dancing Lion")]);
    m.insert(8181, vec![(21010800, "Messmer the Impaler")]);
    m.insert(8183, vec![(28000800, "Midra, Lord of Frenzied Flame")]);
    m.insert(8184, vec![(20010800, "Promised Consort Radahn")]);
    m.insert(8185, vec![(25000800, "Metyr, Mother of Fingers")]);
    m.insert(8700, vec![(13000850, "Godskin Duo")]);
    m.insert(310200, vec![(30070800, "Erdtree Burial Watchdog")]);
    m.insert(410000, vec![(30030800, "Spirit-Caller Snail")]);
    m.insert(417000, vec![(30190800, "Putrid Grave Warden Duelist")]);
    m.insert(419000, vec![(12080800, "Ancestor Spirit")]);
    m.insert(424000, vec![(1050570800, "Death Rite Bird")]);
    m.insert(429000, vec![(15010800, "Unknown Boss (15010800)")]);
    m.insert(9000000, vec![(30000800, "Cemetery Shade")]);
    m.insert(12040000, vec![(12020800, "Valiant Gargoyles")]);
    m.insert(12060000, vec![(12020800, "Valiant Gargoyles")]);
    m.insert(15110000, vec![(1042380850, "Bell Bearing Hunter")]);
    m.insert(15140000, vec![(1049380800, "Commander O'Neil")]);
    m.insert(17020000, vec![(1044360800, "Mad Pumpkin Head")]);
    m.insert(17170000, vec![(32010800, "Stonedigger Troll")]);
    m.insert(21040000, vec![(39200800, "Magma Wyrm Makar")]);
    m.insert(21100000, vec![(1043300800, "Leonine Misbegotten")]);
    m.insert(21150000, vec![(1037530800, "Demi-Human Queen Maggie")]);
    m.insert(22000200, vec![(1042370800, "Crucible Knight")]);
    m.insert(22000400, vec![(1048380800, "Unknown Boss (1048380800)")]);
    m.insert(22000800, vec![(1037500800, "Unknown Boss (1037500800)")]);
    m.insert(22001400, vec![(1040510800, "Unknown Boss (1040510800)")]);
    m
});

/// Boss -> indices into BOSS_DROPS (53 bosses with drops)
pub static BOSS_DROP_INDEX: Lazy<HashMap<u32, Vec<usize>>> = Lazy::new(|| {
    let mut m = HashMap::new();
    m.insert(10000800, vec![0, 1]);
    m.insert(11000800, vec![8, 9]);
    m.insert(11000850, vec![36]);
    m.insert(11050800, vec![15]);
    m.insert(12020800, vec![29, 30]);
    m.insert(12020850, vec![38]);
    m.insert(12030850, vec![19]);
    m.insert(12040800, vec![20]);
    m.insert(12050800, vec![10, 11]);
    m.insert(12080800, vec![39, 40]);
    m.insert(12090800, vec![21]);
    m.insert(13000800, vec![14]);
    m.insert(13000830, vec![18]);
    m.insert(13000850, vec![54]);
    m.insert(14000800, vec![2, 3]);
    m.insert(14000850, vec![32]);
    m.insert(15000800, vec![12, 13]);
    m.insert(15010800, vec![56]);
    m.insert(16000800, vec![6, 7]);
    m.insert(16000850, vec![55]);
    m.insert(19000800, vec![16]);
    m.insert(20000800, vec![57]);
    m.insert(20010800, vec![59]);
    m.insert(21010800, vec![58]);
    m.insert(25000800, vec![61]);
    m.insert(28000800, vec![60]);
    m.insert(30000800, vec![25]);
    m.insert(30030800, vec![47]);
    m.insert(30070800, vec![44]);
    m.insert(30190800, vec![49]);
    m.insert(31190800, vec![42]);
    m.insert(32010800, vec![26]);
    m.insert(35000800, vec![46]);
    m.insert(39200800, vec![31]);
    m.insert(1034450800, vec![34]);
    m.insert(1035500800, vec![45]);
    m.insert(1037500800, vec![52]);
    m.insert(1037530800, vec![27]);
    m.insert(1040510800, vec![53]);
    m.insert(1042330800, vec![41]);
    m.insert(1042370800, vec![50]);
    m.insert(1042380800, vec![43]);
    m.insert(1042380850, vec![24]);
    m.insert(1043300800, vec![22]);
    m.insert(1044350800, vec![33]);
    m.insert(1044360800, vec![23]);
    m.insert(1048370800, vec![35]);
    m.insert(1048380800, vec![51]);
    m.insert(1049380800, vec![28]);
    m.insert(1050570800, vec![48]);
    m.insert(1051560800, vec![37]);
    m.insert(1052520800, vec![17]);
    m.insert(1052380800, vec![4, 5]);
    m
});

/// Boss -> nearby graces (188 bosses)
pub static BOSS_NEARBY_GRACES: Lazy<HashMap<u32, Vec<(u32, f32)>>> = Lazy::new(|| {
    let mut m = HashMap::new();
    m.insert(10000800, vec![(71000, 4.6), (71007, 57.3), (71006, 115.2)]);
    m.insert(10000850, vec![(71001, 11.7), (71002, 58.6), (71008, 91.0), (71003, 114.5), (71004, 186.7)]);
    m.insert(10010800, vec![(71001, 11.7), (71002, 58.6), (71008, 91.0), (71003, 114.5), (71004, 186.7)]);
    m.insert(11000800, vec![(71100, 51.3), (71120, 51.5), (71107, 194.7), (71124, 195.0)]);
    m.insert(11000850, vec![(71101, 0.5), (71121, 0.5), (71107, 111.3), (71124, 112.2), (71105, 158.4)]);
    m.insert(11050800, vec![(71100, 6.5), (71120, 6.6), (71107, 150.2), (71124, 150.5), (71101, 179.7)]);
    m.insert(11050850, vec![(71101, 0.4), (71121, 0.4), (71107, 112.0), (71124, 112.9), (71105, 158.2)]);
    m.insert(12010800, vec![(71210, 98.3), (71219, 119.8), (71216, 190.4)]);
    m.insert(12020800, vec![(71220, 37.8), (71225, 184.0)]);
    m.insert(12020830, vec![(71225, 151.8)]);
    m.insert(12020850, vec![(71221, 21.3), (71226, 163.0)]);
    m.insert(12030800, vec![(71230, 9.5), (71235, 177.8)]);
    m.insert(12030850, vec![(71235, 80.6), (71230, 99.2)]);
    m.insert(12040800, vec![(71240, 59.1), (71213, 133.8)]);
    m.insert(12050800, vec![(71250, 21.5), (71253, 103.3), (71252, 192.0)]);
    m.insert(13000800, vec![(71300, 29.1), (71307, 167.9), (71310, 185.7), (71302, 187.3)]);
    m.insert(13000830, vec![(71301, 1.1)]);
    m.insert(13000850, vec![(71302, 22.1), (71307, 56.5), (71306, 78.8), (71310, 115.4), (71308, 126.7)]);
    m.insert(14000850, vec![(71401, 3.6), (71403, 44.8)]);
    m.insert(15000800, vec![(71500, 11.4), (71504, 135.7), (71503, 189.5), (71502, 199.1)]);
    m.insert(15000850, vec![(71505, 10.1), (71507, 151.7), (71508, 181.6)]);
    m.insert(16000800, vec![(71600, 2.4), (71605, 106.9)]);
    m.insert(16000850, vec![(71601, 8.3), (71602, 152.7), (71603, 159.9), (71607, 165.0)]);
    m.insert(16000860, vec![(71606, 44.5), (71607, 125.5)]);
    m.insert(18000800, vec![(71800, 155.8), (71801, 196.3)]);
    m.insert(18000850, vec![(71800, 51.9), (71801, 80.2)]);
    m.insert(20000800, vec![(72000, 25.7), (72003, 57.2), (72001, 174.8)]);
    m.insert(20010800, vec![(72010, 65.9), (72016, 122.0)]);
    m.insert(21000850, vec![(71500, 11.4), (71504, 135.7), (71503, 189.5), (71502, 199.1)]);
    m.insert(21010800, vec![(71505, 10.1), (71507, 151.7), (71508, 181.6)]);
    m.insert(22000800, vec![(72200, 56.2)]);
    m.insert(25000800, vec![(72500, 6.9)]);
    m.insert(28000800, vec![(72800, 33.4), (72803, 37.3), (72802, 55.7), (72801, 61.2)]);
    m.insert(30000800, vec![(73015, 88.0), (73004, 88.8), (73014, 95.6), (73000, 108.5), (73001, 119.6)]);
    m.insert(30010800, vec![(73016, 77.2), (73001, 109.7)]);
    m.insert(30020800, vec![(73004, 33.3), (73015, 42.9), (73002, 116.2), (73006, 147.6), (73014, 160.8)]);
    m.insert(30030800, vec![(73006, 66.4), (73002, 77.0), (73003, 115.0), (73004, 133.7), (73015, 146.2)]);
    m.insert(30040800, vec![(73000, 78.4), (73014, 89.9), (73015, 114.7), (73004, 116.4), (73001, 149.1)]);
    m.insert(30050800, vec![(73005, 118.4)]);
    m.insert(30050850, vec![(73005, 180.0)]);
    m.insert(30060800, vec![(73003, 42.6), (73002, 54.5), (73006, 113.4), (73011, 117.6), (73014, 134.8)]);
    m.insert(30070800, vec![(73007, 101.1)]);
    m.insert(30090800, vec![(73012, 109.6), (73007, 192.3)]);
    m.insert(30110800, vec![(73011, 123.8), (73014, 169.3), (73000, 179.4)]);
    m.insert(30120800, vec![(73012, 142.9)]);
    m.insert(30130800, vec![(73010, 82.7), (73008, 108.6), (73013, 112.9), (73009, 129.4), (73007, 182.1)]);
    m.insert(30140800, vec![(73001, 100.7), (73014, 132.6), (73011, 140.8), (73000, 144.1), (73002, 182.3)]);
    m.insert(30150800, vec![(73015, 194.6)]);
    m.insert(30160800, vec![(73001, 131.8), (73016, 173.9)]);
    m.insert(30170800, vec![(73020, 172.8)]);
    m.insert(30190800, vec![(73020, 181.1)]);
    m.insert(30200810, vec![(73020, 154.8)]);
    m.insert(31000800, vec![(73101, 91.5), (73121, 124.9), (73103, 155.7)]);
    m.insert(31010800, vec![(73101, 120.3)]);
    m.insert(31020800, vec![(73101, 53.2), (73121, 85.3), (73103, 100.3), (73115, 173.3), (73105, 196.1)]);
    m.insert(31030800, vec![(73121, 73.4), (73103, 112.6), (73110, 143.2), (73101, 151.5), (73105, 161.5)]);
    m.insert(31040800, vec![(73104, 157.7)]);
    m.insert(31050800, vec![(73105, 88.5), (73103, 115.9), (73121, 132.9), (73101, 169.4), (73110, 198.6)]);
    m.insert(31060800, vec![(73111, 76.3), (73106, 120.9), (73120, 120.9), (73117, 178.1), (73110, 197.6)]);
    m.insert(31070800, vec![(73107, 185.8)]);
    m.insert(31090800, vec![(73109, 25.4)]);
    m.insert(31100800, vec![(73117, 83.1), (73110, 90.7), (73103, 95.3), (73121, 97.6), (73120, 112.1)]);
    m.insert(31110800, vec![(73121, 136.2), (73110, 160.6), (73103, 171.0), (73105, 173.8)]);
    m.insert(31120800, vec![(73112, 97.7)]);
    m.insert(31150800, vec![(73115, 67.0), (73101, 149.4), (73103, 189.0)]);
    m.insert(31170800, vec![(73117, 119.2), (73120, 184.8), (73115, 192.6), (73110, 195.4)]);
    m.insert(31180800, vec![(73107, 94.8)]);
    m.insert(31190800, vec![(73119, 60.9)]);
    m.insert(31190850, vec![(73119, 30.3)]);
    m.insert(31200800, vec![(73120, 118.5), (73117, 119.2), (73111, 153.7), (73106, 179.1), (73110, 190.9)]);
    m.insert(31210800, vec![(73101, 115.4), (73121, 127.3), (73103, 159.0)]);
    m.insert(32000800, vec![(73200, 84.0), (73208, 186.3)]);
    m.insert(32010800, vec![(73200, 90.6), (73208, 162.0), (73257, 177.1)]);
    m.insert(32020800, vec![(73208, 94.4), (73257, 106.4), (73200, 123.9)]);
    m.insert(32050800, vec![(73205, 137.5)]);
    m.insert(32070800, vec![(73257, 50.4), (73208, 67.2)]);
    m.insert(32080800, vec![(73257, 130.4), (73208, 158.2)]);
    m.insert(34120800, vec![(73432, 42.6)]);
    m.insert(34130800, vec![(73440, 79.2), (73421, 126.1)]);
    m.insert(35000800, vec![(73500, 0.2), (73504, 122.7), (73502, 144.4)]);
    m.insert(35000850, vec![(73503, 92.2), (73501, 161.5)]);
    m.insert(39200800, vec![(73900, 21.5), (73902, 99.7)]);
    m.insert(41020800, vec![(74102, 89.8)]);
    m.insert(43000800, vec![(74351, 198.3)]);
    m.insert(43010800, vec![(74351, 62.6), (74300, 196.8)]);
    m.insert(1033420800, vec![(76811, 21.8), (76902, 36.8), (76904, 46.1), (76250, 51.5), (76802, 55.4)]);
    m.insert(1033430800, vec![(76222, 34.6), (76218, 44.0), (76800, 53.0), (76914, 58.6), (76252, 61.2)]);
    m.insert(1033450800, vec![(76235, 20.8), (76223, 23.0), (76210, 39.3), (76212, 44.5), (76221, 54.0)]);
    m.insert(1034420800, vec![(76230, 9.2), (76909, 50.4), (76910, 69.3), (76227, 73.2), (76903, 87.9)]);
    m.insert(1034450800, vec![(76223, 26.3), (76455, 40.4), (76218, 44.4), (76221, 46.7), (76102, 49.6)]);
    m.insert(1034480800, vec![(76252, 35.7), (76201, 40.7), (76211, 45.6), (76222, 49.8), (76218, 64.0)]);
    m.insert(1034500800, vec![(76239, 28.3), (76821, 82.7), (76804, 97.0), (76250, 103.4), (76224, 104.6)]);
    m.insert(1035420800, vec![(76223, 32.0), (76212, 36.5), (76221, 38.4), (76235, 39.6), (76914, 51.0)]);
    m.insert(1035500800, vec![(76232, 0.1), (76804, 63.2), (76823, 65.1), (76238, 68.0), (76803, 76.2)]);
    m.insert(1035530800, vec![(76309, 60.5), (76351, 71.9), (76306, 77.1), (76357, 82.8), (76320, 104.7)]);
    m.insert(1036450340, vec![(76212, 32.2), (76203, 38.6), (76202, 42.5), (76456, 48.6), (76235, 49.8)]);
    m.insert(1036480340, vec![(76914, 42.9), (76800, 44.5), (76218, 65.5), (76250, 69.3), (76222, 70.5)]);
    m.insert(1036500800, vec![(76903, 60.1), (76230, 63.4), (76800, 74.7), (76821, 82.1), (76909, 90.9)]);
    m.insert(1036540800, vec![(76352, 80.8), (76500, 119.1), (76502, 123.8), (76311, 130.4), (76314, 141.3)]);
    m.insert(1037420340, vec![(76233, 17.6), (76917, 26.2), (76241, 28.4), (76202, 33.9), (76453, 43.1)]);
    m.insert(1037460800, vec![(76822, 31.4), (76908, 34.3), (76224, 40.7), (76823, 42.7), (76251, 49.0)]);
    m.insert(1037510800, vec![(76303, 64.1), (76944, 68.6), (76301, 91.8), (76354, 98.9), (76355, 108.1)]);
    m.insert(1037530800, vec![(76357, 58.3), (76351, 60.2), (76353, 76.3), (76356, 83.8), (76305, 114.8)]);
    m.insert(1037540810, vec![(76309, 34.3), (76357, 64.1), (76353, 77.5), (76351, 79.7), (76312, 95.1)]);
    m.insert(1038410800, vec![(76219, 29.9), (76242, 44.8), (76204, 47.7), (76916, 51.5), (76220, 53.4)]);
    m.insert(1038480800, vec![(76900, 16.7), (76907, 55.4), (76209, 55.9), (76905, 63.9), (76911, 72.5)]);
    m.insert(1038510800, vec![(76302, 50.9), (76322, 57.7), (73431, 62.2), (76321, 62.6), (76320, 86.2)]);
    m.insert(1038520800, vec![(76350, 45.8), (73431, 71.8), (76322, 98.4), (76321, 119.2), (76302, 121.8)]);
    m.insert(1039430340, vec![(73202, 29.6), (76456, 38.1), (76203, 42.9), (76235, 65.1), (76212, 75.9)]);
    m.insert(1039440800, vec![(76206, 30.5), (76210, 46.3), (76813, 50.8), (76231, 56.2), (76912, 61.7)]);
    m.insert(1039500800, vec![(76300, 58.2), (76306, 70.4), (76320, 78.9), (76943, 89.2), (76321, 136.8)]);
    m.insert(1039540800, vec![(76322, 6.8), (76302, 32.6), (76321, 34.6), (73431, 47.5), (76350, 66.0)]);
    m.insert(1040520800, vec![(76305, 46.6), (76308, 57.3), (76356, 59.4), (76357, 80.2), (76354, 104.0)]);
    m.insert(1040530800, vec![(76350, 35.7), (73431, 44.5), (76322, 58.9), (76302, 82.4), (76321, 82.7)]);
    m.insert(1041500800, vec![(76307, 27.5), (76354, 71.4), (76304, 73.0), (76301, 75.7), (76308, 82.2)]);
    m.insert(1041510800, vec![(76356, 31.0), (76305, 73.6), (76303, 96.0), (76308, 97.1), (76357, 103.9)]);
    m.insert(1041520800, vec![(76351, 62.1), (76353, 64.3), (76357, 71.6), (76312, 104.5), (76356, 117.2)]);
    m.insert(1041530800, vec![(73431, 27.0), (76350, 35.7), (76322, 44.2), (76321, 60.1), (76302, 62.4)]);
    m.insert(1042330800, vec![(76104, 47.4), (76150, 70.7), (73102, 79.6), (76413, 81.4), (76154, 93.8)]);
    m.insert(1042360800, vec![(76411, 20.5), (76113, 22.0), (76412, 26.8), (76106, 30.2), (76120, 32.1)]);
    m.insert(1042370800, vec![(76400, 39.0), (76405, 63.4), (76960, 70.7), (76409, 70.8), (76108, 72.4)]);
    m.insert(1042380800, vec![(76450, 16.6), (73207, 68.8), (76211, 71.5), (76403, 74.8), (76918, 81.4)]);
    m.insert(1042380850, vec![(76118, 10.0), (76418, 46.8), (76960, 57.5), (76252, 64.2), (76201, 64.6)]);
    m.insert(1042550800, vec![(76313, 4.0), (76500, 46.2), (76312, 47.0), (76314, 62.4), (76311, 64.2)]);
    m.insert(1043300800, vec![(76161, 9.3), (76110, 34.3), (76422, 40.7), (76832, 75.2), (76406, 77.9)]);
    m.insert(1043330800, vec![(76106, 31.7), (76155, 40.5), (76108, 42.5), (76412, 42.7), (76113, 50.2)]);
    m.insert(1043360800, vec![(76154, 34.6), (76155, 36.7), (76108, 37.3), (76150, 42.6), (76413, 51.0)]);
    m.insert(1043370800, vec![(76840, 23.4), (76159, 43.8), (76835, 46.2), (76151, 48.5), (76420, 58.3)]);
    m.insert(1043530800, vec![(76311, 76.0), (76852, 101.1), (76500, 105.4), (76313, 126.8), (76314, 132.1)]);
    m.insert(1044320800, vec![(73102, 43.2), (76831, 49.5), (73201, 52.8), (76407, 58.8), (76110, 59.2)]);
    m.insert(1044320850, vec![(76162, 41.9), (76156, 54.6), (73100, 60.1), (76153, 61.5), (76834, 66.7)]);
    m.insert(1044350800, vec![(76111, 32.8), (76100, 49.0), (76413, 58.5), (76404, 63.0), (76411, 63.4)]);
    m.insert(1044360800, vec![(76120, 3.1), (76830, 30.9), (76411, 36.5), (76113, 41.8), (76412, 48.2)]);
    m.insert(1045390800, vec![(76103, 32.5), (76106, 49.3), (76406, 51.3), (76412, 53.5), (76113, 57.6)]);
    m.insert(1045520800, vec![(76311, 54.9), (76500, 79.3), (76852, 90.7), (76352, 92.8), (76313, 117.5)]);
    m.insert(1047400800, vec![(76150, 39.5), (76154, 61.4), (76108, 63.7), (76405, 66.0), (76100, 74.7)]);
    m.insert(1048370800, vec![(76841, 36.0), (76101, 44.4), (76103, 48.7), (76409, 61.1), (76406, 64.0)]);
    m.insert(1048400800, vec![(76402, 20.6), (76841, 80.7), (73201, 91.3), (76451, 93.9), (76409, 97.5)]);
    m.insert(1048410800, vec![(76451, 17.0), (76210, 45.0), (76237, 47.6), (76235, 63.6), (76204, 64.4)]);
    m.insert(1048510800, vec![(76853, 48.7), (76311, 99.7), (76313, 100.2), (76500, 117.4), (76310, 121.9)]);
    m.insert(1048570800, vec![(76551, 16.1), (76550, 137.4)]);
    m.insert(1049370800, vec![(76407, 32.8), (76409, 41.6), (73201, 44.9), (76405, 49.3), (76841, 50.0)]);
    m.insert(1049370850, vec![(76410, 18.1), (76419, 32.5), (76414, 42.8), (76119, 56.6), (76420, 60.0)]);
    m.insert(1049380800, vec![(76412, 3.8), (76113, 8.7), (76106, 16.0), (76834, 37.1), (76411, 37.5)]);
    m.insert(1049390800, vec![(76415, 9.4), (73100, 37.8), (76414, 49.3), (76114, 67.5), (76162, 68.2)]);
    m.insert(1049390850, vec![(76409, 33.2), (76400, 33.7), (76405, 70.7), (76407, 71.4), (76235, 79.5)]);
    m.insert(1049520800, vec![(76311, 73.0), (76500, 94.3), (76314, 113.2), (76313, 122.3), (76852, 122.5)]);
    m.insert(1050560800, vec![(76652, 56.8), (76653, 65.4), (73211, 77.0), (76550, 131.7), (76551, 154.2)]);
    m.insert(1050570800, vec![(76520, 63.4), (76503, 79.0), (76521, 80.5), (76504, 158.4), (76522, 164.6)]);
    m.insert(1050570850, vec![(73019, 45.4), (76550, 87.8), (76652, 157.4), (76653, 170.5), (73211, 185.9)]);
    m.insert(1051360800, vec![(76419, 19.0), (73100, 37.3), (76830, 37.7), (76415, 44.9), (76410, 52.6)]);
    m.insert(1051400800, vec![(76252, 34.2), (76118, 45.8), (76201, 53.7), (76918, 55.5), (76211, 55.7)]);
    m.insert(1051430800, vec![(76234, 21.4), (76213, 33.8), (76810, 37.7), (76220, 52.0), (76200, 55.7)]);
    m.insert(1051570800, vec![(76524, 13.6), (76523, 97.4), (73018, 125.8), (76501, 131.3), (76504, 132.6)]);
    m.insert(1052410800, vec![(76229, 19.6), (76236, 31.6), (76453, 36.0), (76202, 45.5), (76917, 47.7)]);
    m.insert(1052410850, vec![(76118, 37.4), (76201, 39.6), (76241, 53.1), (76960, 57.9), (76418, 62.6)]);
    m.insert(1052520800, vec![(76510, 185.4), (76509, 192.7)]);
    m.insert(1052560800, vec![(76506, 30.8), (76505, 58.8), (73122, 70.0), (76522, 91.3), (73018, 136.1)]);
    m.insert(1053560800, vec![(76520, 95.4), (76503, 105.3), (76507, 142.2), (76508, 153.9), (76505, 185.0)]);
    m.insert(1248550800, vec![(76653, 57.9), (73211, 71.9), (76652, 77.7)]);
    m.insert(1052380800, vec![(76422, 4.2), (76110, 20.3), (76161, 46.7), (76417, 48.2), (76831, 53.8)]);
    m.insert(1054560800, vec![(76505, 95.0), (73122, 105.5), (76522, 111.6), (76506, 112.6), (73017, 126.8)]);
    m.insert(2044450800, vec![(76945, 14.5), (76940, 81.8), (76942, 88.3), (76930, 102.1), (76321, 126.4)]);
    m.insert(2044470800, vec![(76902, 30.6), (76904, 39.9), (76802, 49.5), (76811, 51.1), (76801, 51.8)]);
    m.insert(2045440800, vec![(76213, 18.7), (76220, 30.8), (76916, 31.3), (76216, 32.5), (76242, 39.4)]);
    m.insert(2046380800, vec![(76832, 18.8), (76417, 54.3), (76160, 62.7), (76422, 63.2), (76835, 81.0)]);
    m.insert(2046400800, vec![(76110, 31.7), (76161, 40.7), (76422, 51.8), (73102, 61.1), (76831, 61.7)]);
    m.insert(2046410800, vec![(76850, 62.7), (76456, 99.5), (76229, 102.5), (73202, 106.8), (76801, 108.2)]);
    m.insert(2046450800, vec![(76910, 39.0), (76230, 39.5), (76227, 53.5), (76909, 68.8), (76226, 73.8)]);
    m.insert(2046460800, vec![(76937, 17.8), (76247, 69.5), (76941, 73.5), (76935, 75.6), (76228, 83.9)]);
    m.insert(2047390800, vec![(76415, 22.2), (73100, 28.8), (76414, 38.3), (76419, 39.2), (76830, 59.2)]);
    m.insert(2047450800, vec![(76902, 27.5), (76904, 48.6), (76250, 54.7), (76811, 55.3), (76802, 56.2)]);
    m.insert(2048380850, vec![(76417, 24.3), (76831, 54.4), (76832, 55.6), (76422, 68.1), (73201, 73.4)]);
    m.insert(2048440800, vec![(76823, 10.2), (76238, 48.3), (76822, 52.8), (76906, 53.7), (76232, 55.4)]);
    m.insert(2049410800, vec![(76840, 20.6), (76151, 25.3), (76835, 46.4), (76159, 60.8), (76420, 71.7)]);
    m.insert(2049430800, vec![(76250, 42.2), (76902, 53.6), (76232, 59.2), (76804, 62.6), (76811, 73.0)]);
    m.insert(2049430850, vec![(76910, 19.2), (76227, 19.9), (76226, 34.2), (76909, 54.8), (76230, 62.8)]);
    m.insert(2049450800, vec![(76821, 60.3), (76239, 76.4), (76250, 77.4), (76804, 98.2), (76232, 103.6)]);
    m.insert(2049480800, vec![(76944, 70.6), (76931, 72.3), (76930, 84.2), (76240, 93.1), (76942, 123.6)]);
    m.insert(2050470800, vec![(76942, 46.6), (76930, 59.1), (76945, 98.5), (76247, 119.3), (76239, 120.6)]);
    m.insert(2050480800, vec![(76960, 27.9), (76202, 56.1), (76233, 56.2), (76241, 60.5), (76118, 60.9)]);
    m.insert(2050480860, vec![(76931, 43.5), (76240, 65.2), (76911, 108.3), (76937, 111.3), (76943, 127.1)]);
    m.insert(2051440800, vec![(76118, 26.1), (76418, 36.0), (76404, 49.4), (76111, 55.0), (76960, 56.2)]);
    m.insert(2052400800, vec![(76210, 31.0), (76237, 38.4), (76912, 40.6), (76813, 41.5), (76207, 43.2)]);
    m.insert(2052430800, vec![(76862, 10.8), (76864, 115.6), (76863, 184.2), (76860, 190.0)]);
    m.insert(2052480800, vec![(76239, 55.3), (76232, 87.0), (76942, 106.0), (76804, 115.0), (76250, 122.7)]);
    m.insert(2054390800, vec![(76305, 53.9), (76352, 57.2), (76308, 80.9), (76356, 90.4), (76852, 100.7)]);
    m.insert(2054390850, vec![(76247, 16.6), (76228, 38.6), (76906, 51.1), (76937, 52.5), (76942, 88.9)]);
    m
});

/// Grace -> nearby bosses (313 graces)
pub static GRACE_NEARBY_BOSSES: Lazy<HashMap<u32, Vec<(u32, f32)>>> = Lazy::new(|| {
    let mut m = HashMap::new();
    m.insert(71000, vec![(10000800, 4.6)]);
    m.insert(71001, vec![(10000850, 11.7), (10010800, 11.7)]);
    m.insert(71002, vec![(10000850, 58.6), (10010800, 58.6)]);
    m.insert(71003, vec![(10000850, 114.5), (10010800, 114.5)]);
    m.insert(71004, vec![(10000850, 186.7), (10010800, 186.7)]);
    m.insert(71006, vec![(10000800, 115.2)]);
    m.insert(71007, vec![(10000800, 57.3)]);
    m.insert(71008, vec![(10000850, 91.0), (10010800, 91.0)]);
    m.insert(71100, vec![(11050800, 6.5), (11000800, 51.3)]);
    m.insert(71101, vec![(11050850, 0.4), (11000850, 0.5), (11050800, 179.7)]);
    m.insert(71105, vec![(11050850, 158.2), (11000850, 158.4)]);
    m.insert(71107, vec![(11000850, 111.3), (11050850, 112.0), (11050800, 150.2), (11000800, 194.7)]);
    m.insert(71120, vec![(11050800, 6.6), (11000800, 51.5)]);
    m.insert(71121, vec![(11050850, 0.4), (11000850, 0.5)]);
    m.insert(71124, vec![(11000850, 112.2), (11050850, 112.9), (11050800, 150.5), (11000800, 195.0)]);
    m.insert(71210, vec![(12010800, 98.3)]);
    m.insert(71213, vec![(12040800, 133.8)]);
    m.insert(71216, vec![(12010800, 190.4)]);
    m.insert(71219, vec![(12010800, 119.8)]);
    m.insert(71220, vec![(12020800, 37.8)]);
    m.insert(71221, vec![(12020850, 21.3)]);
    m.insert(71225, vec![(12020830, 151.8), (12020800, 184.0)]);
    m.insert(71226, vec![(12020850, 163.0)]);
    m.insert(71230, vec![(12030800, 9.5), (12030850, 99.2)]);
    m.insert(71235, vec![(12030850, 80.6), (12030800, 177.8)]);
    m.insert(71240, vec![(12040800, 59.1)]);
    m.insert(71250, vec![(12050800, 21.5)]);
    m.insert(71252, vec![(12050800, 192.0)]);
    m.insert(71253, vec![(12050800, 103.3)]);
    m.insert(71300, vec![(13000800, 29.1)]);
    m.insert(71301, vec![(13000830, 1.1)]);
    m.insert(71302, vec![(13000850, 22.1), (13000800, 187.3)]);
    m.insert(71306, vec![(13000850, 78.8)]);
    m.insert(71307, vec![(13000850, 56.5), (13000800, 167.9)]);
    m.insert(71308, vec![(13000850, 126.7)]);
    m.insert(71310, vec![(13000850, 115.4), (13000800, 185.7)]);
    m.insert(71401, vec![(14000850, 3.6)]);
    m.insert(71403, vec![(14000850, 44.8)]);
    m.insert(71500, vec![(15000800, 11.4), (21000850, 11.4)]);
    m.insert(71502, vec![(15000800, 199.1), (21000850, 199.1)]);
    m.insert(71503, vec![(15000800, 189.5), (21000850, 189.5)]);
    m.insert(71504, vec![(15000800, 135.7), (21000850, 135.7)]);
    m.insert(71505, vec![(15000850, 10.1), (21010800, 10.1)]);
    m.insert(71507, vec![(15000850, 151.7), (21010800, 151.7)]);
    m.insert(71508, vec![(15000850, 181.6), (21010800, 181.6)]);
    m.insert(71600, vec![(16000800, 2.4)]);
    m.insert(71601, vec![(16000850, 8.3)]);
    m.insert(71602, vec![(16000850, 152.7)]);
    m.insert(71603, vec![(16000850, 159.9)]);
    m.insert(71605, vec![(16000800, 106.9)]);
    m.insert(71606, vec![(16000860, 44.5)]);
    m.insert(71607, vec![(16000860, 125.5), (16000850, 165.0)]);
    m.insert(71800, vec![(18000850, 51.9), (18000800, 155.8)]);
    m.insert(71801, vec![(18000850, 80.2), (18000800, 196.3)]);
    m.insert(72000, vec![(20000800, 25.7)]);
    m.insert(72001, vec![(20000800, 174.8)]);
    m.insert(72003, vec![(20000800, 57.2)]);
    m.insert(72010, vec![(20010800, 65.9)]);
    m.insert(72016, vec![(20010800, 122.0)]);
    m.insert(72200, vec![(22000800, 56.2)]);
    m.insert(72500, vec![(25000800, 6.9)]);
    m.insert(72800, vec![(28000800, 33.4)]);
    m.insert(72801, vec![(28000800, 61.2)]);
    m.insert(72802, vec![(28000800, 55.7)]);
    m.insert(72803, vec![(28000800, 37.3)]);
    m.insert(73000, vec![(30040800, 78.4), (30000800, 108.5), (30140800, 144.1), (30110800, 179.4)]);
    m.insert(73001, vec![(30140800, 100.7), (30010800, 109.7), (30000800, 119.6), (30160800, 131.8), (30040800, 149.1)]);
    m.insert(73002, vec![(30060800, 54.5), (30030800, 77.0), (30020800, 116.2), (30140800, 182.3)]);
    m.insert(73003, vec![(30060800, 42.6), (30030800, 115.0)]);
    m.insert(73004, vec![(30020800, 33.3), (30000800, 88.8), (30040800, 116.4), (30030800, 133.7)]);
    m.insert(73005, vec![(30050800, 118.4), (30050850, 180.0)]);
    m.insert(73006, vec![(30030800, 66.4), (30060800, 113.4), (30020800, 147.6)]);
    m.insert(73007, vec![(30070800, 101.1), (30130800, 182.1), (30090800, 192.3)]);
    m.insert(73008, vec![(30130800, 108.6)]);
    m.insert(73009, vec![(30130800, 129.4)]);
    m.insert(73010, vec![(30130800, 82.7)]);
    m.insert(73011, vec![(30060800, 117.6), (30110800, 123.8), (30140800, 140.8)]);
    m.insert(73012, vec![(30090800, 109.6), (30120800, 142.9)]);
    m.insert(73013, vec![(30130800, 112.9)]);
    m.insert(73014, vec![(30040800, 89.9), (30000800, 95.6), (30140800, 132.6), (30060800, 134.8), (30020800, 160.8), (30110800, 169.3)]);
    m.insert(73015, vec![(30020800, 42.9), (30000800, 88.0), (30040800, 114.7), (30030800, 146.2), (30150800, 194.6)]);
    m.insert(73016, vec![(30010800, 77.2), (30160800, 173.9)]);
    m.insert(73017, vec![(1054560800, 126.8)]);
    m.insert(73018, vec![(1051570800, 125.8), (1052560800, 136.1)]);
    m.insert(73019, vec![(1050570850, 45.4)]);
    m.insert(73020, vec![(30200810, 154.8), (30170800, 172.8), (30190800, 181.1)]);
    m.insert(73100, vec![(2047390800, 28.8), (1051360800, 37.3), (1049390800, 37.8), (1044320850, 60.1)]);
    m.insert(73101, vec![(31020800, 53.2), (31000800, 91.5), (31210800, 115.4), (31010800, 120.3), (31150800, 149.4), (31030800, 151.5), (31050800, 169.4)]);
    m.insert(73102, vec![(1044320800, 43.2), (2046400800, 61.1), (1042330800, 79.6)]);
    m.insert(73103, vec![(31100800, 95.3), (31020800, 100.3), (31030800, 112.6), (31050800, 115.9), (31000800, 155.7), (31210800, 159.0), (31110800, 171.0), (31150800, 189.0)]);
    m.insert(73104, vec![(31040800, 157.7)]);
    m.insert(73105, vec![(31050800, 88.5), (31030800, 161.5), (31110800, 173.8), (31020800, 196.1)]);
    m.insert(73106, vec![(31060800, 120.9), (31200800, 179.1)]);
    m.insert(73107, vec![(31180800, 94.8), (31070800, 185.8)]);
    m.insert(73109, vec![(31090800, 25.4)]);
    m.insert(73110, vec![(31100800, 90.7), (31030800, 143.2), (31110800, 160.6), (31200800, 190.9), (31170800, 195.4), (31060800, 197.6), (31050800, 198.6)]);
    m.insert(73111, vec![(31060800, 76.3), (31200800, 153.7)]);
    m.insert(73112, vec![(31120800, 97.7)]);
    m.insert(73115, vec![(31150800, 67.0), (31020800, 173.3), (31170800, 192.6)]);
    m.insert(73117, vec![(31100800, 83.1), (31170800, 119.2), (31200800, 119.2), (31060800, 178.1)]);
    m.insert(73119, vec![(31190850, 30.3), (31190800, 60.9)]);
    m.insert(73120, vec![(31100800, 112.1), (31200800, 118.5), (31060800, 120.9), (31170800, 184.8)]);
    m.insert(73121, vec![(31030800, 73.4), (31020800, 85.3), (31100800, 97.6), (31000800, 124.9), (31210800, 127.3), (31050800, 132.9), (31110800, 136.2)]);
    m.insert(73122, vec![(1052560800, 70.0), (1054560800, 105.5)]);
    m.insert(73200, vec![(32000800, 84.0), (32010800, 90.6), (32020800, 123.9)]);
    m.insert(73201, vec![(1049370800, 44.9), (1044320800, 52.8), (2048380850, 73.4), (1048400800, 91.3)]);
    m.insert(73202, vec![(1039430340, 29.6), (2046410800, 106.8)]);
    m.insert(73205, vec![(32050800, 137.5)]);
    m.insert(73207, vec![(1042380800, 68.8)]);
    m.insert(73208, vec![(32070800, 67.2), (32020800, 94.4), (32080800, 158.2), (32010800, 162.0), (32000800, 186.3)]);
    m.insert(73211, vec![(1248550800, 71.9), (1050560800, 77.0), (1050570850, 185.9)]);
    m.insert(73257, vec![(32070800, 50.4), (32020800, 106.4), (32080800, 130.4), (32010800, 177.1)]);
    m.insert(73421, vec![(34130800, 126.1)]);
    m.insert(73431, vec![(1041530800, 27.0), (1040530800, 44.5), (1039540800, 47.5), (1038510800, 62.2), (1038520800, 71.8)]);
    m.insert(73432, vec![(34120800, 42.6)]);
    m.insert(73440, vec![(34130800, 79.2)]);
    m.insert(73500, vec![(35000800, 0.2)]);
    m.insert(73501, vec![(35000850, 161.5)]);
    m.insert(73502, vec![(35000800, 144.4)]);
    m.insert(73503, vec![(35000850, 92.2)]);
    m.insert(73504, vec![(35000800, 122.7)]);
    m.insert(73900, vec![(39200800, 21.5)]);
    m.insert(73902, vec![(39200800, 99.7)]);
    m.insert(74102, vec![(41020800, 89.8)]);
    m.insert(74300, vec![(43010800, 196.8)]);
    m.insert(74351, vec![(43010800, 62.6), (43000800, 198.3)]);
    m.insert(76100, vec![(1044350800, 49.0), (1047400800, 74.7)]);
    m.insert(76101, vec![(1048370800, 44.4)]);
    m.insert(76102, vec![(1034450800, 49.6)]);
    m.insert(76103, vec![(1045390800, 32.5), (1048370800, 48.7)]);
    m.insert(76104, vec![(1042330800, 47.4)]);
    m.insert(76106, vec![(1049380800, 16.0), (1042360800, 30.2), (1043330800, 31.7), (1045390800, 49.3)]);
    m.insert(76108, vec![(1043360800, 37.3), (1043330800, 42.5), (1047400800, 63.7), (1042370800, 72.4)]);
    m.insert(76110, vec![(1052380800, 20.3), (2046400800, 31.7), (1043300800, 34.3), (1044320800, 59.2)]);
    m.insert(76111, vec![(1044350800, 32.8), (2051440800, 55.0)]);
    m.insert(76113, vec![(1049380800, 8.7), (1042360800, 22.0), (1044360800, 41.8), (1043330800, 50.2), (1045390800, 57.6)]);
    m.insert(76114, vec![(1049390800, 67.5)]);
    m.insert(76118, vec![(1042380850, 10.0), (2051440800, 26.1), (1052410850, 37.4), (1051400800, 45.8), (2050480800, 60.9)]);
    m.insert(76119, vec![(1049370850, 56.6)]);
    m.insert(76120, vec![(1044360800, 3.1), (1042360800, 32.1)]);
    m.insert(76150, vec![(1047400800, 39.5), (1043360800, 42.6), (1042330800, 70.7)]);
    m.insert(76151, vec![(2049410800, 25.3), (1043370800, 48.5)]);
    m.insert(76153, vec![(1044320850, 61.5)]);
    m.insert(76154, vec![(1043360800, 34.6), (1047400800, 61.4), (1042330800, 93.8)]);
    m.insert(76155, vec![(1043360800, 36.7), (1043330800, 40.5)]);
    m.insert(76156, vec![(1044320850, 54.6)]);
    m.insert(76159, vec![(1043370800, 43.8), (2049410800, 60.8)]);
    m.insert(76160, vec![(2046380800, 62.7)]);
    m.insert(76161, vec![(1043300800, 9.3), (2046400800, 40.7), (1052380800, 46.7)]);
    m.insert(76162, vec![(1044320850, 41.9), (1049390800, 68.2)]);
    m.insert(76200, vec![(1051430800, 55.7)]);
    m.insert(76201, vec![(1052410850, 39.6), (1034480800, 40.7), (1051400800, 53.7), (1042380850, 64.6)]);
    m.insert(76202, vec![(1037420340, 33.9), (1036450340, 42.5), (1052410800, 45.5), (2050480800, 56.1)]);
    m.insert(76203, vec![(1036450340, 38.6), (1039430340, 42.9)]);
    m.insert(76204, vec![(1038410800, 47.7), (1048410800, 64.4)]);
    m.insert(76206, vec![(1039440800, 30.5)]);
    m.insert(76207, vec![(2052400800, 43.2)]);
    m.insert(76209, vec![(1038480800, 55.9)]);
    m.insert(76210, vec![(2052400800, 31.0), (1033450800, 39.3), (1048410800, 45.0), (1039440800, 46.3)]);
    m.insert(76211, vec![(1034480800, 45.6), (1051400800, 55.7), (1042380800, 71.5)]);
    m.insert(76212, vec![(1036450340, 32.2), (1035420800, 36.5), (1033450800, 44.5), (1039430340, 75.9)]);
    m.insert(76213, vec![(2045440800, 18.7), (1051430800, 33.8)]);
    m.insert(76216, vec![(2045440800, 32.5)]);
    m.insert(76218, vec![(1033430800, 44.0), (1034450800, 44.4), (1034480800, 64.0), (1036480340, 65.5)]);
    m.insert(76219, vec![(1038410800, 29.9)]);
    m.insert(76220, vec![(2045440800, 30.8), (1051430800, 52.0), (1038410800, 53.4)]);
    m.insert(76221, vec![(1035420800, 38.4), (1034450800, 46.7), (1033450800, 54.0)]);
    m.insert(76222, vec![(1033430800, 34.6), (1034480800, 49.8), (1036480340, 70.5)]);
    m.insert(76223, vec![(1033450800, 23.0), (1034450800, 26.3), (1035420800, 32.0)]);
    m.insert(76224, vec![(1037460800, 40.7), (1034500800, 104.6)]);
    m.insert(76226, vec![(2049430850, 34.2), (2046450800, 73.8)]);
    m.insert(76227, vec![(2049430850, 19.9), (2046450800, 53.5), (1034420800, 73.2)]);
    m.insert(76228, vec![(2054390850, 38.6), (2046460800, 83.9)]);
    m.insert(76229, vec![(1052410800, 19.6), (2046410800, 102.5)]);
    m.insert(76230, vec![(1034420800, 9.2), (2046450800, 39.5), (2049430850, 62.8), (1036500800, 63.4)]);
    m.insert(76231, vec![(1039440800, 56.2)]);
    m.insert(76232, vec![(1035500800, 0.1), (2048440800, 55.4), (2049430800, 59.2), (2052480800, 87.0), (2049450800, 103.6)]);
    m.insert(76233, vec![(1037420340, 17.6), (2050480800, 56.2)]);
    m.insert(76234, vec![(1051430800, 21.4)]);
    m.insert(76235, vec![(1033450800, 20.8), (1035420800, 39.6), (1036450340, 49.8), (1048410800, 63.6), (1039430340, 65.1), (1049390850, 79.5)]);
    m.insert(76236, vec![(1052410800, 31.6)]);
    m.insert(76237, vec![(2052400800, 38.4), (1048410800, 47.6)]);
    m.insert(76238, vec![(2048440800, 48.3), (1035500800, 68.0)]);
    m.insert(76239, vec![(1034500800, 28.3), (2052480800, 55.3), (2049450800, 76.4), (2050470800, 120.6)]);
    m.insert(76240, vec![(2050480860, 65.2), (2049480800, 93.1)]);
    m.insert(76241, vec![(1037420340, 28.4), (1052410850, 53.1), (2050480800, 60.5)]);
    m.insert(76242, vec![(2045440800, 39.4), (1038410800, 44.8)]);
    m.insert(76247, vec![(2054390850, 16.6), (2046460800, 69.5), (2050470800, 119.3)]);
    m.insert(76250, vec![(2049430800, 42.2), (1033420800, 51.5), (2047450800, 54.7), (1036480340, 69.3), (2049450800, 77.4), (1034500800, 103.4), (2052480800, 122.7)]);
    m.insert(76251, vec![(1037460800, 49.0)]);
    m.insert(76252, vec![(1051400800, 34.2), (1034480800, 35.7), (1033430800, 61.2), (1042380850, 64.2)]);
    m.insert(76300, vec![(1039500800, 58.2)]);
    m.insert(76301, vec![(1041500800, 75.7), (1037510800, 91.8)]);
    m.insert(76302, vec![(1039540800, 32.6), (1038510800, 50.9), (1041530800, 62.4), (1040530800, 82.4), (1038520800, 121.8)]);
    m.insert(76303, vec![(1037510800, 64.1), (1041510800, 96.0)]);
    m.insert(76304, vec![(1041500800, 73.0)]);
    m.insert(76305, vec![(1040520800, 46.6), (2054390800, 53.9), (1041510800, 73.6), (1037530800, 114.8)]);
    m.insert(76306, vec![(1039500800, 70.4), (1035530800, 77.1)]);
    m.insert(76307, vec![(1041500800, 27.5)]);
    m.insert(76308, vec![(1040520800, 57.3), (2054390800, 80.9), (1041500800, 82.2), (1041510800, 97.1)]);
    m.insert(76309, vec![(1037540810, 34.3), (1035530800, 60.5)]);
    m.insert(76310, vec![(1048510800, 121.9)]);
    m.insert(76311, vec![(1045520800, 54.9), (1042550800, 64.2), (1049520800, 73.0), (1043530800, 76.0), (1048510800, 99.7), (1036540800, 130.4)]);
    m.insert(76312, vec![(1042550800, 47.0), (1037540810, 95.1), (1041520800, 104.5)]);
    m.insert(76313, vec![(1042550800, 4.0), (1048510800, 100.2), (1045520800, 117.5), (1049520800, 122.3), (1043530800, 126.8)]);
    m.insert(76314, vec![(1042550800, 62.4), (1049520800, 113.2), (1043530800, 132.1), (1036540800, 141.3)]);
    m.insert(76320, vec![(1039500800, 78.9), (1038510800, 86.2), (1035530800, 104.7)]);
    m.insert(76321, vec![(1039540800, 34.6), (1041530800, 60.1), (1038510800, 62.6), (1040530800, 82.7), (1038520800, 119.2), (2044450800, 126.4), (1039500800, 136.8)]);
    m.insert(76322, vec![(1039540800, 6.8), (1041530800, 44.2), (1038510800, 57.7), (1040530800, 58.9), (1038520800, 98.4)]);
    m.insert(76350, vec![(1040530800, 35.7), (1041530800, 35.7), (1038520800, 45.8), (1039540800, 66.0)]);
    m.insert(76351, vec![(1037530800, 60.2), (1041520800, 62.1), (1035530800, 71.9), (1037540810, 79.7)]);
    m.insert(76352, vec![(2054390800, 57.2), (1036540800, 80.8), (1045520800, 92.8)]);
    m.insert(76353, vec![(1041520800, 64.3), (1037530800, 76.3), (1037540810, 77.5)]);
    m.insert(76354, vec![(1041500800, 71.4), (1037510800, 98.9), (1040520800, 104.0)]);
    m.insert(76355, vec![(1037510800, 108.1)]);
    m.insert(76356, vec![(1041510800, 31.0), (1040520800, 59.4), (1037530800, 83.8), (2054390800, 90.4), (1041520800, 117.2)]);
    m.insert(76357, vec![(1037530800, 58.3), (1037540810, 64.1), (1041520800, 71.6), (1040520800, 80.2), (1035530800, 82.8), (1041510800, 103.9)]);
    m.insert(76400, vec![(1049390850, 33.7), (1042370800, 39.0)]);
    m.insert(76402, vec![(1048400800, 20.6)]);
    m.insert(76403, vec![(1042380800, 74.8)]);
    m.insert(76404, vec![(2051440800, 49.4), (1044350800, 63.0)]);
    m.insert(76405, vec![(1049370800, 49.3), (1042370800, 63.4), (1047400800, 66.0), (1049390850, 70.7)]);
    m.insert(76406, vec![(1045390800, 51.3), (1048370800, 64.0), (1043300800, 77.9)]);
    m.insert(76407, vec![(1049370800, 32.8), (1044320800, 58.8), (1049390850, 71.4)]);
    m.insert(76409, vec![(1049390850, 33.2), (1049370800, 41.6), (1048370800, 61.1), (1042370800, 70.8), (1048400800, 97.5)]);
    m.insert(76410, vec![(1049370850, 18.1), (1051360800, 52.6)]);
    m.insert(76411, vec![(1042360800, 20.5), (1044360800, 36.5), (1049380800, 37.5), (1044350800, 63.4)]);
    m.insert(76412, vec![(1049380800, 3.8), (1042360800, 26.8), (1043330800, 42.7), (1044360800, 48.2), (1045390800, 53.5)]);
    m.insert(76413, vec![(1043360800, 51.0), (1044350800, 58.5), (1042330800, 81.4)]);
    m.insert(76414, vec![(2047390800, 38.3), (1049370850, 42.8), (1049390800, 49.3)]);
    m.insert(76415, vec![(1049390800, 9.4), (2047390800, 22.2), (1051360800, 44.9)]);
    m.insert(76417, vec![(2048380850, 24.3), (1052380800, 48.2), (2046380800, 54.3)]);
    m.insert(76418, vec![(2051440800, 36.0), (1042380850, 46.8), (1052410850, 62.6)]);
    m.insert(76419, vec![(1051360800, 19.0), (1049370850, 32.5), (2047390800, 39.2)]);
    m.insert(76420, vec![(1043370800, 58.3), (1049370850, 60.0), (2049410800, 71.7)]);
    m.insert(76422, vec![(1052380800, 4.2), (1043300800, 40.7), (2046400800, 51.8), (2046380800, 63.2), (2048380850, 68.1)]);
    m.insert(76450, vec![(1042380800, 16.6)]);
    m.insert(76451, vec![(1048410800, 17.0), (1048400800, 93.9)]);
    m.insert(76453, vec![(1052410800, 36.0), (1037420340, 43.1)]);
    m.insert(76455, vec![(1034450800, 40.4)]);
    m.insert(76456, vec![(1039430340, 38.1), (1036450340, 48.6), (2046410800, 99.5)]);
    m.insert(76500, vec![(1042550800, 46.2), (1045520800, 79.3), (1049520800, 94.3), (1043530800, 105.4), (1048510800, 117.4), (1036540800, 119.1)]);
    m.insert(76501, vec![(1051570800, 131.3)]);
    m.insert(76502, vec![(1036540800, 123.8)]);
    m.insert(76503, vec![(1050570800, 79.0), (1053560800, 105.3)]);
    m.insert(76504, vec![(1051570800, 132.6), (1050570800, 158.4)]);
    m.insert(76505, vec![(1052560800, 58.8), (1054560800, 95.0), (1053560800, 185.0)]);
    m.insert(76506, vec![(1052560800, 30.8), (1054560800, 112.6)]);
    m.insert(76507, vec![(1053560800, 142.2)]);
    m.insert(76508, vec![(1053560800, 153.9)]);
    m.insert(76509, vec![(1052520800, 192.7)]);
    m.insert(76510, vec![(1052520800, 185.4)]);
    m.insert(76520, vec![(1050570800, 63.4), (1053560800, 95.4)]);
    m.insert(76521, vec![(1050570800, 80.5)]);
    m.insert(76522, vec![(1052560800, 91.3), (1054560800, 111.6), (1050570800, 164.6)]);
    m.insert(76523, vec![(1051570800, 97.4)]);
    m.insert(76524, vec![(1051570800, 13.6)]);
    m.insert(76550, vec![(1050570850, 87.8), (1050560800, 131.7), (1048570800, 137.4)]);
    m.insert(76551, vec![(1048570800, 16.1), (1050560800, 154.2)]);
    m.insert(76652, vec![(1050560800, 56.8), (1248550800, 77.7), (1050570850, 157.4)]);
    m.insert(76653, vec![(1248550800, 57.9), (1050560800, 65.4), (1050570850, 170.5)]);
    m.insert(76800, vec![(1036480340, 44.5), (1033430800, 53.0), (1036500800, 74.7)]);
    m.insert(76801, vec![(2044470800, 51.8), (2046410800, 108.2)]);
    m.insert(76802, vec![(2044470800, 49.5), (1033420800, 55.4), (2047450800, 56.2)]);
    m.insert(76803, vec![(1035500800, 76.2)]);
    m.insert(76804, vec![(2049430800, 62.6), (1035500800, 63.2), (1034500800, 97.0), (2049450800, 98.2), (2052480800, 115.0)]);
    m.insert(76810, vec![(1051430800, 37.7)]);
    m.insert(76811, vec![(1033420800, 21.8), (2044470800, 51.1), (2047450800, 55.3), (2049430800, 73.0)]);
    m.insert(76813, vec![(2052400800, 41.5), (1039440800, 50.8)]);
    m.insert(76821, vec![(2049450800, 60.3), (1036500800, 82.1), (1034500800, 82.7)]);
    m.insert(76822, vec![(1037460800, 31.4), (2048440800, 52.8)]);
    m.insert(76823, vec![(2048440800, 10.2), (1037460800, 42.7), (1035500800, 65.1)]);
    m.insert(76830, vec![(1044360800, 30.9), (1051360800, 37.7), (2047390800, 59.2)]);
    m.insert(76831, vec![(1044320800, 49.5), (1052380800, 53.8), (2048380850, 54.4), (2046400800, 61.7)]);
    m.insert(76832, vec![(2046380800, 18.8), (2048380850, 55.6), (1043300800, 75.2)]);
    m.insert(76834, vec![(1049380800, 37.1), (1044320850, 66.7)]);
    m.insert(76835, vec![(1043370800, 46.2), (2049410800, 46.4), (2046380800, 81.0)]);
    m.insert(76840, vec![(2049410800, 20.6), (1043370800, 23.4)]);
    m.insert(76841, vec![(1048370800, 36.0), (1049370800, 50.0), (1048400800, 80.7)]);
    m.insert(76850, vec![(2046410800, 62.7)]);
    m.insert(76852, vec![(1045520800, 90.7), (2054390800, 100.7), (1043530800, 101.1), (1049520800, 122.5)]);
    m.insert(76853, vec![(1048510800, 48.7)]);
    m.insert(76860, vec![(2052430800, 190.0)]);
    m.insert(76862, vec![(2052430800, 10.8)]);
    m.insert(76863, vec![(2052430800, 184.2)]);
    m.insert(76864, vec![(2052430800, 115.6)]);
    m.insert(76900, vec![(1038480800, 16.7)]);
    m.insert(76902, vec![(2047450800, 27.5), (2044470800, 30.6), (1033420800, 36.8), (2049430800, 53.6)]);
    m.insert(76903, vec![(1036500800, 60.1), (1034420800, 87.9)]);
    m.insert(76904, vec![(2044470800, 39.9), (1033420800, 46.1), (2047450800, 48.6)]);
    m.insert(76905, vec![(1038480800, 63.9)]);
    m.insert(76906, vec![(2054390850, 51.1), (2048440800, 53.7)]);
    m.insert(76907, vec![(1038480800, 55.4)]);
    m.insert(76908, vec![(1037460800, 34.3)]);
    m.insert(76909, vec![(1034420800, 50.4), (2049430850, 54.8), (2046450800, 68.8), (1036500800, 90.9)]);
    m.insert(76910, vec![(2049430850, 19.2), (2046450800, 39.0), (1034420800, 69.3)]);
    m.insert(76911, vec![(1038480800, 72.5), (2050480860, 108.3)]);
    m.insert(76912, vec![(2052400800, 40.6), (1039440800, 61.7)]);
    m.insert(76914, vec![(1036480340, 42.9), (1035420800, 51.0), (1033430800, 58.6)]);
    m.insert(76916, vec![(2045440800, 31.3), (1038410800, 51.5)]);
    m.insert(76917, vec![(1037420340, 26.2), (1052410800, 47.7)]);
    m.insert(76918, vec![(1051400800, 55.5), (1042380800, 81.4)]);
    m.insert(76930, vec![(2050470800, 59.1), (2049480800, 84.2), (2044450800, 102.1)]);
    m.insert(76931, vec![(2050480860, 43.5), (2049480800, 72.3)]);
    m.insert(76935, vec![(2046460800, 75.6)]);
    m.insert(76937, vec![(2046460800, 17.8), (2054390850, 52.5), (2050480860, 111.3)]);
    m.insert(76940, vec![(2044450800, 81.8)]);
    m.insert(76941, vec![(2046460800, 73.5)]);
    m.insert(76942, vec![(2050470800, 46.6), (2044450800, 88.3), (2054390850, 88.9), (2052480800, 106.0), (2049480800, 123.6)]);
    m.insert(76943, vec![(1039500800, 89.2), (2050480860, 127.1)]);
    m.insert(76944, vec![(1037510800, 68.6), (2049480800, 70.6)]);
    m.insert(76945, vec![(2044450800, 14.5), (2050470800, 98.5)]);
    m.insert(76960, vec![(2050480800, 27.9), (2051440800, 56.2), (1042380850, 57.5), (1052410850, 57.9), (1042370800, 70.7)]);
    m
});
