//! Landmark database - Points of interest on the map (non-Grace locations)
//! 
//! Generated from WorldMapPointParam.param.xml via extracted_event_flags.json
//! Total landmarks: 308 entries

pub mod landmarks {
    use std::{collections::HashMap, sync::Mutex};
    use once_cell::sync::Lazy;

    /// Landmark locations on the map (dungeons, ruins, churches, etc.)
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Copy, PartialOrd, Ord)]
    pub enum Landmark {
        JaggedPeakFootOfTheJaggedPeakIgon,
        StormveilCastle,
        StrandedGraveyard,
        FringefolkHerosGrave,
        StormfootCatacombs,
        DeathtouchedCatacombs,
        MurkwaterCatacombs,
        TombswardCave,
        GrovesideCave,
        CoastalCave,
        HighroadCave,
        LimgraveTunnels,
        DivineTowerOfLimgrave,
        ChurchOfElleh,
        ChurchOfDragonCommunion,
        ThirdChurchOfMarika,
        MistwoodRuins,
        WaypointRuins,
        DragonBurntRuins,
        GatefrontRuins,
        SummonwaterVillage,
        ArtistsShack,
        WarmastersShack,
        StormhillShack,
        ForlornHoundEvergaol,
        StormhillEvergaol,
        BridgeOfSacrifice,
        SiofraRiverWell,
        FortHaight,
        MinorErdtree,
        Stormgate,
        TombswardCatacombs,
        ImpalersCatacombs,
        MurkwaterCave,
        EarthboreCave,
        MorneTunnel,
        FourthChurchOfMarika,
        ChurchOfPilgrimage,
        CalluBaptismalChurch,
        IsolatedMerchantsShack,
        AilingVillage,
        OridyssRise,
        ForestLookoutTower,
        TowerOfReturn,
        WeepingEvergaol,
        WitchbaneRuins,
        TombswardRuins,
        DemiHumanForestRuins,
        CastleMorne,
        MinorErdtree2,
        AcademyOfRayaLucaria,
        BlackKnifeCatacombs,
        RoadsEndCatacombs,
        CliffbottomCatacombs,
        StillwaterCave,
        LakesideCrystalCave,
        AcademyCrystalCave,
        RayaLucariaCrystalTunnel,
        CarianStudyHall,
        DivineTowerOfLiurnia,
        ChurchOfIrith,
        ChurchOfVows,
        RoseChurch,
        BellumChurch,
        ChurchOfInhibition,
        PurifiedRuins,
        KingsrealmRuins,
        LaskyarRuins,
        SlumberingWolfsShack,
        BoilprawnShack,
        ArtistsShack2,
        RevengersShack,
        VillageOfTheAlbinaurics,
        FrenziedFlameVillage,
        Jarburg,
        HighwayLookoutTower,
        FrenzyFlamingTower,
        MalefactorsEvergaol,
        CuckoosEvergaol,
        RoyalGraveEvergaol,
        AinselRiverWell,
        ConvertedTower,
        TestusRise,
        SeluvissRise,
        RannisRise,
        RennasRise,
        ConvertedFringeTower,
        CariaManor,
        MinorErdtree3,
        MinorErdtree4,
        AcademyGateTown,
        TempleQuarter,
        TheFourBelfries,
        UldPalaceRuins,
        ThreeSisters,
        CathedralOfManusCeles,
        RingleadersEvergaol,
        DeepAinselWell,
        ChelonasRise,
        MoonfolkRuins,
        LunarEstateRuins,
        LeyndellRoyalCapital,
        SaintedHerosGrave,
        GelmirHerosGrave,
        AurizaHerosGrave,
        UnsightlyCatacombs,
        WyndhamCatacombs,
        AurizaSideTomb,
        SeethewaterCave,
        VolcanoCave,
        PerfumersGrotto,
        SagesCave,
        OldAltusTunnel,
        SealedTunnel,
        AltusTunnel,
        DivineTowerOfWestAltus,
        SubterraneanShunningGrounds,
        RuinStrewnPrecipice,
        GrandLiftOfDectus,
        StormcallerChurch,
        SecondChurchOfMarika,
        MinorErdtreeChurch,
        WoodfolkRuins,
        LuxRuins,
        StTrinasHideaway,
        HermitMerchantsShack,
        WestWindmillPasture,
        EastWindmillPasture,
        VillageWindmillPasture,
        DominulaWindmillVillage,
        MirageRise,
        HighwayLookoutTower2,
        GoldenLineageEvergaol,
        TheShadedCastle,
        MinorErdtree5,
        MinorErdtree6,
        PerfumersRuins,
        VolcanoManor,
        WrithebloodRuins,
        CorpseStenchShack,
        HermitVillage,
        FortLaiedd,
        MinorErdtree7,
        WyndhamRuins,
        HermitsShack,
        CraftsmansShack,
        MinorErdtreeCatacombs,
        CaelidCatacombs,
        WarDeadCatacombs,
        DragonbarrowCave,
        AbandonedCave,
        GaolCave,
        GaelTunnel,
        SelliaCrystalTunnel,
        SmolderingChurch,
        CathedralOfDragonCommunion,
        ChurchOfThePlague,
        ForsakenRuins,
        CaelidWaypointRuins,
        StreetOfSagesRuins,
        CaelemRuins,
        ShackOfTheRotting,
        GowrysShack,
        FortGael,
        SwampLookoutTower,
        SelliaGateway,
        DeepSiofraWell,
        SelliaTownOfSorcery,
        RedmaneCastle,
        MinorErdtree8,
        WailingDunes,
        SelliaHideaway,
        DivineTowerOfCaelid,
        IsolatedMerchantsShack2,
        SelliaEvergaol,
        LennesRise,
        FortFaroth,
        MinorErdtree9,
        BestialSanctum,
        GiantConqueringHerosGrave,
        GiantsMountaintopCatacombs,
        ConsecratedSnowfieldCatacombs,
        CaveOfTheForlorn,
        SpiritcallerCave,
        YeloughAnixTunnel,
        DivineTowerOfEastAltus,
        FirstChurchOfMarika,
        ChurchOfRepose,
        ZamorRuins,
        StargazersRuins,
        ShackOfTheLofty,
        LordContendersEvergaol,
        HereticalRise,
        GuardiansGarrison,
        GrandLiftOfRold,
        CastleSol,
        MinorErdtree10,
        ForgeOfTheGiants,
        MiquellasHaligtree,
        ElphaelBraceOfTheHaligtree,
        HiddenPathToTheHaligtree,
        ApostateDerelict,
        YeloughAnixRuins,
        OrdinaLiturgicalTown,
        AlbinauricRise,
        MinorErdtree11,
        UhlPalaceRuins,
        UhlPalaceRuins2,
        NokstellaEternalCity,
        GrandCloister,
        NokronEternalCity,
        NightsSacredGround,
        SiofraAqueduct,
        HallowhornGrounds,
        HallowhornGrounds2,
        MohgwynDynastyMausoleum,
        CrumblingFarumAzula,
        IsolatedDivineTower,
        RoyalColosseum,
        LimgraveColosseum,
        CaelidColosseum,
        BeluratGaol,
        MiquellasCross,
        MiquellasCross2,
        AbandonedAilingVillage,
        ChurchOfConsolation,
        ChurchOfBenediction,
        ScorchedRuins,
        ProspectTown,
        WesternNamelessMausoleum,
        RunDownTravelersRest,
        EllacGreatbridge,
        ArtistsShack3,
        LegacyDungeonUnused,
        DragonsPit,
        RuinedForgeLavaIntake,
        FogRiftCatacombs,
        MiquellasCross3,
        SuppressingPillar,
        EldersHovel,
        CastleEnsis,
        MiquellasCross4,
        FingerRuinsOfRhia,
        FingerWeaversHovel,
        MiquellasCross5,
        SouthernNamelessMausoleum,
        FingerRuinsOfRhia2,
        LamentersGaol,
        GrandAltarOfDragonCommunion,
        MidrasManse,
        AbandonedChurch,
        StoneCoffinFissure,
        MiquellasCross6,
        BeluratTowerSettlement,
        MiquellasCross7,
        EnirIlim,
        MiquellasCross8,
        MiquellasCross9,
        MiquellasCross10,
        FortOfReprimand,
        MiquellasCross11,
        FogRiftFort,
        ChurchOfTheCrusade,
        CathedralOfManusMetyr,
        MoorthRuins,
        RabbathsRise,
        WhippingHut,
        BonnyVillage,
        FingerRuinsOfMiyr,
        FingerRuinsOfMiyr2,
        ScorpionRiverCatacombs,
        BonnyGaol,
        TaylewsRuinedForge,
        Poi62918,
        RivermouthCave,
        TempleTownRuins,
        NorthernNamelessMausoleum,
        ScadutreeChalice,
        AlbinauricsShack,
        FingerRuinsOfDheo,
        ShamanVillage,
        FingerRuinsOfDheo2,
        RuinedForgeOfStarfallPast,
        MiquellasCross12,
        RuinsOfUnte,
        EasternNamelessMausoleum,
        VillageOfFlies,
        DarklightCatacombs,
        ScadutreeBase,
        ShadowKeep,
        MiquellasCross13,
        CatacombGuidanceLimgraveChurchOfEllehStrandedGraveyardExit,
        CatacombGuidanceStormhillSaintsbridgeDeathtouchedCatacombsEntranceHighroadCaveEntrance,
        CatacombGuidanceLimgraveMurkwaterCoastMurkwaterCatacombsEntrance,
        CatacombGuidanceWeepingPeninsulaChurchOfPilgrimageDemiHumanForestRuins,
        CatacombGuidanceWeepingPeninsulaImpalersCatacombsEntrance,
        CatacombGuidanceBellumHighwayFrenziedFlameVillageMinorErdtree,
        CatacombGuidanceLiurniaOfTheLakesRevengersShack,
        CatacombGuidanceLiurniaOfTheLakesLiurniaHighwayNorth,
        CatacombGuidanceAltusPlateauPerfumersRuinsUnsightlyCatacombsEntrance,
        CatacombGuidanceAltusPlateauWyndhamRuinsWyndhamCatacombsEntrance,
        CatacombGuidanceCapitalOutskirtsCapitalRampartAurizaSideTombEntrance,
        CatacombGuidanceCaelidCaelemRuinsForsakenRuinsMinorErdtreeMinorErdtreeCatacombsEntrance,
        CatacombGuidanceCaelidSouthwestOfCaelidHighwaySouth,
        CatacombGuidanceGreyollsDragonbarrowFortFaroth,
        CatacombGuidanceMountaintopsOfTheGiantsEastZamorRuinsFlamePeakGiantConqueringHerosGraveEntrance,
        CatacombGuidanceConsecratedSnowfieldNortheastFoggyAreaInnerConsecratedSnowfield,
        DivineTowerOfEastAltusTheRoldRoute,
    }

    /// Static map of Landmark -> (flag_id, display_name)
    /// 
    /// Use this to look up the event flag ID and display name for each landmark.
    pub static LANDMARKS: Lazy<Mutex<HashMap<Landmark, (u32, &'static str)>>> = Lazy::new(|| {
        Mutex::new(HashMap::from([
            (Landmark::JaggedPeakFootOfTheJaggedPeakIgon, (6001, "Jagged Peak: Foot of the Jagged Peak - Igon")),
            (Landmark::StormveilCastle, (62100, "Stormveil Castle")),
            (Landmark::StrandedGraveyard, (62101, "Stranded Graveyard")),
            (Landmark::FringefolkHerosGrave, (62102, "Fringefolk Hero's Grave")),
            (Landmark::StormfootCatacombs, (62103, "Stormfoot Catacombs")),
            (Landmark::DeathtouchedCatacombs, (62104, "Deathtouched Catacombs")),
            (Landmark::MurkwaterCatacombs, (62105, "Murkwater Catacombs")),
            (Landmark::TombswardCave, (62106, "Tombsward Cave")),
            (Landmark::GrovesideCave, (62107, "Groveside Cave")),
            (Landmark::CoastalCave, (62108, "Coastal Cave")),
            (Landmark::HighroadCave, (62109, "Highroad Cave")),
            (Landmark::LimgraveTunnels, (62110, "Limgrave Tunnels")),
            (Landmark::DivineTowerOfLimgrave, (62111, "Divine Tower of Limgrave")),
            (Landmark::ChurchOfElleh, (62120, "Church of Elleh")),
            (Landmark::ChurchOfDragonCommunion, (62121, "Church of Dragon Communion")),
            (Landmark::ThirdChurchOfMarika, (62122, "Third Church of Marika")),
            (Landmark::MistwoodRuins, (62123, "Mistwood Ruins")),
            (Landmark::WaypointRuins, (62124, "Waypoint Ruins")),
            (Landmark::DragonBurntRuins, (62125, "Dragon-Burnt Ruins")),
            (Landmark::GatefrontRuins, (62126, "Gatefront Ruins")),
            (Landmark::SummonwaterVillage, (62127, "Summonwater Village")),
            (Landmark::ArtistsShack, (62128, "Artist's Shack")),
            (Landmark::WarmastersShack, (62129, "Warmaster's Shack")),
            (Landmark::StormhillShack, (62130, "Stormhill Shack")),
            (Landmark::ForlornHoundEvergaol, (62131, "Forlorn Hound Evergaol")),
            (Landmark::StormhillEvergaol, (62132, "Stormhill Evergaol")),
            (Landmark::BridgeOfSacrifice, (62133, "Bridge of Sacrifice")),
            (Landmark::SiofraRiverWell, (62134, "Siofra River Well")),
            (Landmark::FortHaight, (62135, "Fort Haight")),
            (Landmark::MinorErdtree, (62137, "Minor Erdtree")),
            (Landmark::Stormgate, (62138, "Stormgate")),
            (Landmark::TombswardCatacombs, (62150, "Tombsward Catacombs")),
            (Landmark::ImpalersCatacombs, (62151, "Impaler's Catacombs")),
            (Landmark::MurkwaterCave, (62152, "Murkwater Cave")),
            (Landmark::EarthboreCave, (62153, "Earthbore Cave")),
            (Landmark::MorneTunnel, (62154, "Morne Tunnel")),
            (Landmark::FourthChurchOfMarika, (62170, "Fourth Church of Marika")),
            (Landmark::ChurchOfPilgrimage, (62171, "Church of Pilgrimage")),
            (Landmark::CalluBaptismalChurch, (62172, "Callu Baptismal Church")),
            (Landmark::IsolatedMerchantsShack, (62173, "Isolated Merchant's Shack")),
            (Landmark::AilingVillage, (62174, "Ailing Village")),
            (Landmark::OridyssRise, (62175, "Oridys's Rise")),
            (Landmark::ForestLookoutTower, (62176, "Forest Lookout Tower")),
            (Landmark::TowerOfReturn, (62177, "Tower of Return")),
            (Landmark::WeepingEvergaol, (62178, "Weeping Evergaol")),
            (Landmark::WitchbaneRuins, (62180, "Witchbane Ruins")),
            (Landmark::TombswardRuins, (62181, "Tombsward Ruins")),
            (Landmark::DemiHumanForestRuins, (62182, "Demi-Human Forest Ruins")),
            (Landmark::CastleMorne, (62183, "Castle Morne")),
            (Landmark::MinorErdtree2, (62184, "Minor Erdtree")),
            (Landmark::AcademyOfRayaLucaria, (62200, "Academy of Raya Lucaria")),
            (Landmark::BlackKnifeCatacombs, (62201, "Black Knife Catacombs")),
            (Landmark::RoadsEndCatacombs, (62202, "Road's End Catacombs")),
            (Landmark::CliffbottomCatacombs, (62203, "Cliffbottom Catacombs")),
            (Landmark::StillwaterCave, (62204, "Stillwater Cave")),
            (Landmark::LakesideCrystalCave, (62205, "Lakeside Crystal Cave")),
            (Landmark::AcademyCrystalCave, (62206, "Academy Crystal Cave")),
            (Landmark::RayaLucariaCrystalTunnel, (62207, "Raya Lucaria Crystal Tunnel")),
            (Landmark::CarianStudyHall, (62208, "Carian Study Hall")),
            (Landmark::DivineTowerOfLiurnia, (62209, "Divine Tower of Liurnia")),
            (Landmark::ChurchOfIrith, (62220, "Church of Irith")),
            (Landmark::ChurchOfVows, (62221, "Church of Vows")),
            (Landmark::RoseChurch, (62222, "Rose Church")),
            (Landmark::BellumChurch, (62223, "Bellum Church")),
            (Landmark::ChurchOfInhibition, (62224, "Church of Inhibition")),
            (Landmark::PurifiedRuins, (62225, "Purified Ruins")),
            (Landmark::KingsrealmRuins, (62226, "Kingsrealm Ruins")),
            (Landmark::LaskyarRuins, (62227, "Laskyar Ruins")),
            (Landmark::SlumberingWolfsShack, (62228, "Slumbering Wolf's Shack")),
            (Landmark::BoilprawnShack, (62229, "Boilprawn Shack")),
            (Landmark::ArtistsShack2, (62230, "Artist's Shack")),
            (Landmark::RevengersShack, (62231, "Revenger's Shack")),
            (Landmark::VillageOfTheAlbinaurics, (62232, "Village of the Albinaurics")),
            (Landmark::FrenziedFlameVillage, (62233, "Frenzied Flame Village")),
            (Landmark::Jarburg, (62234, "Jarburg")),
            (Landmark::HighwayLookoutTower, (62235, "Highway Lookout Tower")),
            (Landmark::FrenzyFlamingTower, (62236, "Frenzy-Flaming Tower")),
            (Landmark::MalefactorsEvergaol, (62237, "Malefactor's Evergaol")),
            (Landmark::CuckoosEvergaol, (62238, "Cuckoo's Evergaol")),
            (Landmark::RoyalGraveEvergaol, (62239, "Royal Grave Evergaol")),
            (Landmark::AinselRiverWell, (62240, "Ainsel River Well")),
            (Landmark::ConvertedTower, (62241, "Converted Tower")),
            (Landmark::TestusRise, (62242, "Testu's Rise")),
            (Landmark::SeluvissRise, (62243, "Seluvis's Rise")),
            (Landmark::RannisRise, (62244, "Ranni's Rise")),
            (Landmark::RennasRise, (62245, "Renna's Rise")),
            (Landmark::ConvertedFringeTower, (62246, "Converted Fringe Tower")),
            (Landmark::CariaManor, (62247, "Caria Manor")),
            (Landmark::MinorErdtree3, (62248, "Minor Erdtree")),
            (Landmark::MinorErdtree4, (62249, "Minor Erdtree")),
            (Landmark::AcademyGateTown, (62250, "Academy Gate Town")),
            (Landmark::TempleQuarter, (62251, "Temple Quarter")),
            (Landmark::TheFourBelfries, (62252, "The Four Belfries")),
            (Landmark::UldPalaceRuins, (62253, "Uld Palace Ruins")),
            (Landmark::ThreeSisters, (62254, "Three Sisters")),
            (Landmark::CathedralOfManusCeles, (62280, "Cathedral of Manus Celes")),
            (Landmark::RingleadersEvergaol, (62281, "Ringleader's Evergaol")),
            (Landmark::DeepAinselWell, (62282, "Deep Ainsel Well")),
            (Landmark::ChelonasRise, (62283, "Chelona's Rise")),
            (Landmark::MoonfolkRuins, (62284, "Moonfolk Ruins")),
            (Landmark::LunarEstateRuins, (62285, "Lunar Estate Ruins")),
            (Landmark::LeyndellRoyalCapital, (62300, "Leyndell, Royal Capital")),
            (Landmark::SaintedHerosGrave, (62310, "Sainted Hero's Grave")),
            (Landmark::GelmirHerosGrave, (62311, "Gelmir Hero's Grave")),
            (Landmark::AurizaHerosGrave, (62312, "Auriza Hero's Grave")),
            (Landmark::UnsightlyCatacombs, (62313, "Unsightly Catacombs")),
            (Landmark::WyndhamCatacombs, (62314, "Wyndham Catacombs")),
            (Landmark::AurizaSideTomb, (62315, "Auriza Side Tomb")),
            (Landmark::SeethewaterCave, (62316, "Seethewater Cave")),
            (Landmark::VolcanoCave, (62317, "Volcano Cave")),
            (Landmark::PerfumersGrotto, (62318, "Perfumer's Grotto")),
            (Landmark::SagesCave, (62319, "Sage's Cave")),
            (Landmark::OldAltusTunnel, (62320, "Old Altus Tunnel")),
            (Landmark::SealedTunnel, (62321, "Sealed Tunnel")),
            (Landmark::AltusTunnel, (62322, "Altus Tunnel")),
            (Landmark::DivineTowerOfWestAltus, (62323, "Divine Tower of West Altus")),
            (Landmark::SubterraneanShunningGrounds, (62324, "Subterranean Shunning-Grounds")),
            (Landmark::RuinStrewnPrecipice, (62325, "Ruin-Strewn Precipice")),
            (Landmark::GrandLiftOfDectus, (62330, "Grand Lift of Dectus")),
            (Landmark::StormcallerChurch, (62331, "Stormcaller Church")),
            (Landmark::SecondChurchOfMarika, (62332, "Second Church of Marika")),
            (Landmark::MinorErdtreeChurch, (62333, "Minor Erdtree Church")),
            (Landmark::WoodfolkRuins, (62334, "Woodfolk Ruins")),
            (Landmark::LuxRuins, (62335, "Lux Ruins")),
            (Landmark::StTrinasHideaway, (62336, "St. Trina's Hideaway")),
            (Landmark::HermitMerchantsShack, (62337, "Hermit Merchant's Shack")),
            (Landmark::WestWindmillPasture, (62338, "West Windmill Pasture")),
            (Landmark::EastWindmillPasture, (62339, "East Windmill Pasture")),
            (Landmark::VillageWindmillPasture, (62340, "Village Windmill Pasture")),
            (Landmark::DominulaWindmillVillage, (62341, "Dominula, Windmill Village")),
            (Landmark::MirageRise, (62342, "Mirage Rise")),
            (Landmark::HighwayLookoutTower2, (62343, "Highway Lookout Tower")),
            (Landmark::GoldenLineageEvergaol, (62344, "Golden Lineage Evergaol")),
            (Landmark::TheShadedCastle, (62345, "The Shaded Castle")),
            (Landmark::MinorErdtree5, (62346, "Minor Erdtree")),
            (Landmark::MinorErdtree6, (62347, "Minor Erdtree")),
            (Landmark::PerfumersRuins, (62348, "Perfumer's Ruins")),
            (Landmark::VolcanoManor, (62360, "Volcano Manor")),
            (Landmark::WrithebloodRuins, (62380, "Writheblood Ruins")),
            (Landmark::CorpseStenchShack, (62381, "Corpse-Stench Shack")),
            (Landmark::HermitVillage, (62382, "Hermit Village")),
            (Landmark::FortLaiedd, (62383, "Fort Laiedd")),
            (Landmark::MinorErdtree7, (62384, "Minor Erdtree")),
            (Landmark::WyndhamRuins, (62385, "Wyndham Ruins")),
            (Landmark::HermitsShack, (62386, "Hermit's Shack")),
            (Landmark::CraftsmansShack, (62389, "Craftsman's Shack")),
            (Landmark::MinorErdtreeCatacombs, (62410, "Minor Erdtree Catacombs")),
            (Landmark::CaelidCatacombs, (62411, "Caelid Catacombs")),
            (Landmark::WarDeadCatacombs, (62412, "War-Dead Catacombs")),
            (Landmark::DragonbarrowCave, (62413, "Dragonbarrow Cave")),
            (Landmark::AbandonedCave, (62414, "Abandoned Cave")),
            (Landmark::GaolCave, (62415, "Gaol Cave")),
            (Landmark::GaelTunnel, (62416, "Gael Tunnel")),
            (Landmark::SelliaCrystalTunnel, (62417, "Sellia Crystal Tunnel")),
            (Landmark::SmolderingChurch, (62420, "Smoldering Church")),
            (Landmark::CathedralOfDragonCommunion, (62421, "Cathedral of Dragon Communion")),
            (Landmark::ChurchOfThePlague, (62422, "Church of the Plague")),
            (Landmark::ForsakenRuins, (62423, "Forsaken Ruins")),
            (Landmark::CaelidWaypointRuins, (62424, "Caelid Waypoint Ruins")),
            (Landmark::StreetOfSagesRuins, (62425, "Street of Sages Ruins")),
            (Landmark::CaelemRuins, (62426, "Caelem Ruins")),
            (Landmark::ShackOfTheRotting, (62427, "Shack of the Rotting")),
            (Landmark::GowrysShack, (62428, "Gowry's Shack")),
            (Landmark::FortGael, (62429, "Fort Gael")),
            (Landmark::SwampLookoutTower, (62430, "Swamp Lookout Tower")),
            (Landmark::SelliaGateway, (62432, "Sellia Gateway")),
            (Landmark::DeepSiofraWell, (62434, "Deep Siofra Well")),
            (Landmark::SelliaTownOfSorcery, (62435, "Sellia, Town of Sorcery")),
            (Landmark::RedmaneCastle, (62436, "Redmane Castle")),
            (Landmark::MinorErdtree8, (62437, "Minor Erdtree")),
            (Landmark::WailingDunes, (62438, "Wailing Dunes")),
            (Landmark::SelliaHideaway, (62460, "Sellia Hideaway")),
            (Landmark::DivineTowerOfCaelid, (62461, "Divine Tower of Caelid")),
            (Landmark::IsolatedMerchantsShack2, (62470, "Isolated Merchant's Shack")),
            (Landmark::SelliaEvergaol, (62471, "Sellia Evergaol")),
            (Landmark::LennesRise, (62472, "Lenne's Rise")),
            (Landmark::FortFaroth, (62473, "Fort Faroth")),
            (Landmark::MinorErdtree9, (62474, "Minor Erdtree")),
            (Landmark::BestialSanctum, (62475, "Bestial Sanctum")),
            (Landmark::GiantConqueringHerosGrave, (62510, "Giant-Conquering Hero's Grave")),
            (Landmark::GiantsMountaintopCatacombs, (62511, "Giants' Mountaintop Catacombs")),
            (Landmark::ConsecratedSnowfieldCatacombs, (62512, "Consecrated Snowfield Catacombs")),
            (Landmark::CaveOfTheForlorn, (62513, "Cave of the Forlorn")),
            (Landmark::SpiritcallerCave, (62514, "Spiritcaller Cave")),
            (Landmark::YeloughAnixTunnel, (62515, "Yelough Anix Tunnel")),
            (Landmark::DivineTowerOfEastAltus, (62516, "Divine Tower of East Altus")),
            (Landmark::FirstChurchOfMarika, (62520, "First Church of Marika")),
            (Landmark::ChurchOfRepose, (62521, "Church of Repose")),
            (Landmark::ZamorRuins, (62522, "Zamor Ruins")),
            (Landmark::StargazersRuins, (62523, "Stargazers' Ruins")),
            (Landmark::ShackOfTheLofty, (62524, "Shack of the Lofty")),
            (Landmark::LordContendersEvergaol, (62525, "Lord Contender's Evergaol")),
            (Landmark::HereticalRise, (62526, "Heretical Rise")),
            (Landmark::GuardiansGarrison, (62527, "Guardians' Garrison")),
            (Landmark::GrandLiftOfRold, (62528, "Grand Lift of Rold")),
            (Landmark::CastleSol, (62529, "Castle Sol")),
            (Landmark::MinorErdtree10, (62530, "Minor Erdtree")),
            (Landmark::ForgeOfTheGiants, (62531, "Forge of the Giants")),
            (Landmark::MiquellasHaligtree, (62550, "Miquella's Haligtree")),
            (Landmark::ElphaelBraceOfTheHaligtree, (62551, "Elphael, Brace of the Haligtree")),
            (Landmark::HiddenPathToTheHaligtree, (62560, "Hidden Path to the Haligtree")),
            (Landmark::ApostateDerelict, (62570, "Apostate Derelict")),
            (Landmark::YeloughAnixRuins, (62571, "Yelough Anix Ruins")),
            (Landmark::OrdinaLiturgicalTown, (62572, "Ordina, Liturgical Town")),
            (Landmark::AlbinauricRise, (62573, "Albinauric Rise")),
            (Landmark::MinorErdtree11, (62574, "Minor Erdtree")),
            (Landmark::UhlPalaceRuins, (62610, "Uhl Palace Ruins")),
            (Landmark::UhlPalaceRuins2, (62620, "Uhl Palace Ruins")),
            (Landmark::NokstellaEternalCity, (62621, "Nokstella, Eternal City")),
            (Landmark::GrandCloister, (62622, "Grand Cloister")),
            (Landmark::NokronEternalCity, (62630, "Nokron, Eternal City")),
            (Landmark::NightsSacredGround, (62631, "Night's Sacred Ground")),
            (Landmark::SiofraAqueduct, (62632, "Siofra Aqueduct")),
            (Landmark::HallowhornGrounds, (62633, "Hallowhorn Grounds")),
            (Landmark::HallowhornGrounds2, (62634, "Hallowhorn Grounds")),
            (Landmark::MohgwynDynastyMausoleum, (62640, "Mohgwyn Dynasty Mausoleum")),
            (Landmark::CrumblingFarumAzula, (62700, "Crumbling Farum Azula")),
            (Landmark::IsolatedDivineTower, (62710, "Isolated Divine Tower")),
            (Landmark::RoyalColosseum, (62720, "Royal Colosseum")),
            (Landmark::LimgraveColosseum, (62730, "Limgrave Colosseum")),
            (Landmark::CaelidColosseum, (62740, "Caelid Colosseum")),
            (Landmark::BeluratGaol, (62800, "Belurat Gaol")),
            (Landmark::MiquellasCross, (62805, "Miquella's Cross")),
            (Landmark::MiquellasCross2, (62806, "Miquella's Cross")),
            (Landmark::AbandonedAilingVillage, (62807, "Abandoned Ailing Village")),
            (Landmark::ChurchOfConsolation, (62808, "Church of Consolation")),
            (Landmark::ChurchOfBenediction, (62809, "Church of Benediction")),
            (Landmark::ScorchedRuins, (62810, "Scorched Ruins")),
            (Landmark::ProspectTown, (62811, "Prospect Town")),
            (Landmark::WesternNamelessMausoleum, (62812, "Western Nameless Mausoleum")),
            (Landmark::RunDownTravelersRest, (62813, "Run-Down Traveler's Rest")),
            (Landmark::EllacGreatbridge, (62814, "Ellac Greatbridge")),
            (Landmark::ArtistsShack3, (62815, "Artist's Shack")),
            (Landmark::LegacyDungeonUnused, (62820, "Legacy Dungeon - Unused")),
            (Landmark::DragonsPit, (62821, "Dragon's Pit")),
            (Landmark::RuinedForgeLavaIntake, (62822, "Ruined Forge Lava Intake")),
            (Landmark::FogRiftCatacombs, (62823, "Fog Rift Catacombs")),
            (Landmark::MiquellasCross3, (62825, "Miquella's Cross")),
            (Landmark::SuppressingPillar, (62826, "Suppressing Pillar")),
            (Landmark::EldersHovel, (62827, "Elder's Hovel")),
            (Landmark::CastleEnsis, (62830, "Castle Ensis")),
            (Landmark::MiquellasCross4, (62831, "Miquella's Cross")),
            (Landmark::FingerRuinsOfRhia, (62840, "Finger Ruins of Rhia")),
            (Landmark::FingerWeaversHovel, (62841, "Finger-Weaver's Hovel")),
            (Landmark::MiquellasCross5, (62842, "Miquella's Cross")),
            (Landmark::SouthernNamelessMausoleum, (62843, "Southern Nameless Mausoleum")),
            (Landmark::FingerRuinsOfRhia2, (62844, "Finger Ruins of Rhia")),
            (Landmark::LamentersGaol, (62850, "Lamenter's Gaol")),
            (Landmark::GrandAltarOfDragonCommunion, (62855, "Grand Altar of Dragon Communion")),
            (Landmark::MidrasManse, (62860, "Midra's Manse")),
            (Landmark::AbandonedChurch, (62865, "Abandoned Church")),
            (Landmark::StoneCoffinFissure, (62870, "Stone Coffin Fissure")),
            (Landmark::MiquellasCross6, (62871, "Miquella's Cross")),
            (Landmark::BeluratTowerSettlement, (62880, "Belurat, Tower Settlement")),
            (Landmark::MiquellasCross7, (62881, "Miquella's Cross")),
            (Landmark::EnirIlim, (62890, "Enir-Ilim")),
            (Landmark::MiquellasCross8, (62891, "Miquella's Cross")),
            (Landmark::MiquellasCross9, (62900, "Miquella's Cross")),
            (Landmark::MiquellasCross10, (62901, "Miquella's Cross")),
            (Landmark::FortOfReprimand, (62902, "Fort of Reprimand")),
            (Landmark::MiquellasCross11, (62903, "Miquella's Cross")),
            (Landmark::FogRiftFort, (62904, "Fog Rift Fort")),
            (Landmark::ChurchOfTheCrusade, (62905, "Church of the Crusade")),
            (Landmark::CathedralOfManusMetyr, (62906, "Cathedral of Manus Metyr")),
            (Landmark::MoorthRuins, (62907, "Moorth Ruins")),
            (Landmark::RabbathsRise, (62908, "Rabbath's Rise")),
            (Landmark::WhippingHut, (62909, "Whipping Hut")),
            (Landmark::BonnyVillage, (62910, "Bonny Village")),
            (Landmark::FingerRuinsOfMiyr, (62911, "Finger Ruins of Miyr")),
            (Landmark::FingerRuinsOfMiyr2, (62912, "Finger Ruins of Miyr")),
            (Landmark::ScorpionRiverCatacombs, (62915, "Scorpion River Catacombs")),
            (Landmark::BonnyGaol, (62916, "Bonny Gaol")),
            (Landmark::TaylewsRuinedForge, (62917, "Taylew's Ruined Forge")),
            (Landmark::Poi62918, (62918, "POI_62918")),
            (Landmark::RivermouthCave, (62919, "Rivermouth Cave")),
            (Landmark::TempleTownRuins, (62920, "Temple Town Ruins")),
            (Landmark::NorthernNamelessMausoleum, (62921, "Northern Nameless Mausoleum")),
            (Landmark::ScadutreeChalice, (62931, "Scadutree Chalice")),
            (Landmark::AlbinauricsShack, (62932, "Albinauric's Shack")),
            (Landmark::FingerRuinsOfDheo, (62940, "Finger Ruins of Dheo")),
            (Landmark::ShamanVillage, (62941, "Shaman Village")),
            (Landmark::FingerRuinsOfDheo2, (62942, "Finger Ruins of Dheo")),
            (Landmark::RuinedForgeOfStarfallPast, (62943, "Ruined Forge of Starfall Past")),
            (Landmark::MiquellasCross12, (62950, "Miquella's Cross")),
            (Landmark::RuinsOfUnte, (62960, "Ruins of Unte")),
            (Landmark::EasternNamelessMausoleum, (62961, "Eastern Nameless Mausoleum")),
            (Landmark::VillageOfFlies, (62962, "Village of Flies")),
            (Landmark::DarklightCatacombs, (62965, "Darklight Catacombs")),
            (Landmark::ScadutreeBase, (62970, "Scadutree Base")),
            (Landmark::ShadowKeep, (62980, "Shadow Keep")),
            (Landmark::MiquellasCross13, (62981, "Miquella's Cross")),
            (Landmark::CatacombGuidanceLimgraveChurchOfEllehStrandedGraveyardExit, (78190, "Catacomb Guidance: Limgrave - Church of Elleh, Stranded Graveyard Exit")),
            (Landmark::CatacombGuidanceStormhillSaintsbridgeDeathtouchedCatacombsEntranceHighroadCaveEntrance, (78192, "Catacomb Guidance: Stormhill - Saintsbridge, Deathtouched Catacombs Entrance, Highroad Cave Entrance")),
            (Landmark::CatacombGuidanceLimgraveMurkwaterCoastMurkwaterCatacombsEntrance, (78194, "Catacomb Guidance: Limgrave - Murkwater Coast, Murkwater Catacombs Entrance")),
            (Landmark::CatacombGuidanceWeepingPeninsulaChurchOfPilgrimageDemiHumanForestRuins, (78196, "Catacomb Guidance: Weeping Peninsula - Church of Pilgrimage, Demi-Human Forest Ruins")),
            (Landmark::CatacombGuidanceWeepingPeninsulaImpalersCatacombsEntrance, (78198, "Catacomb Guidance: Weeping Peninsula - Impaler's Catacombs Entrance")),
            (Landmark::CatacombGuidanceBellumHighwayFrenziedFlameVillageMinorErdtree, (78290, "Catacomb Guidance: Bellum Highway - Frenzied Flame Village, Minor Erdtree")),
            (Landmark::CatacombGuidanceLiurniaOfTheLakesRevengersShack, (78292, "Catacomb Guidance: Liurnia of the Lakes - Revenger's Shack")),
            (Landmark::CatacombGuidanceLiurniaOfTheLakesLiurniaHighwayNorth, (78294, "Catacomb Guidance: Liurnia of the Lakes - Liurnia Highway North")),
            (Landmark::CatacombGuidanceAltusPlateauPerfumersRuinsUnsightlyCatacombsEntrance, (78390, "Catacomb Guidance: Altus Plateau - Perfumer's Ruins, Unsightly Catacombs Entrance")),
            (Landmark::CatacombGuidanceAltusPlateauWyndhamRuinsWyndhamCatacombsEntrance, (78392, "Catacomb Guidance: Altus Plateau - Wyndham Ruins, Wyndham Catacombs Entrance")),
            (Landmark::CatacombGuidanceCapitalOutskirtsCapitalRampartAurizaSideTombEntrance, (78394, "Catacomb Guidance: Capital Outskirts - Capital Rampart, Auriza Side Tomb Entrance")),
            (Landmark::CatacombGuidanceCaelidCaelemRuinsForsakenRuinsMinorErdtreeMinorErdtreeCatacombsEntrance, (78490, "Catacomb Guidance: Caelid - Caelem Ruins, Forsaken Ruins, Minor Erdtree, Minor Erdtree Catacombs Entrance")),
            (Landmark::CatacombGuidanceCaelidSouthwestOfCaelidHighwaySouth, (78492, "Catacomb Guidance: Caelid - Southwest of Caelid Highway South")),
            (Landmark::CatacombGuidanceGreyollsDragonbarrowFortFaroth, (78494, "Catacomb Guidance: Greyoll's Dragonbarrow - Fort Faroth")),
            (Landmark::CatacombGuidanceMountaintopsOfTheGiantsEastZamorRuinsFlamePeakGiantConqueringHerosGraveEntrance, (78592, "Catacomb Guidance: Mountaintops of the Giants - East Zamor Ruins; Flame Peak - Giant-Conquering Hero's Grave Entrance")),
            (Landmark::CatacombGuidanceConsecratedSnowfieldNortheastFoggyAreaInnerConsecratedSnowfield, (78594, "Catacomb Guidance: Consecrated Snowfield - Northeast Foggy Area, Inner Consecrated Snowfield")),
            (Landmark::DivineTowerOfEastAltusTheRoldRoute, (11109687, "Divine Tower of East Altus - The Rold Route")),
        ]))
    });

    /// Reverse lookup: flag_id -> Landmark
    pub static LANDMARK_BY_FLAG: Lazy<Mutex<HashMap<u32, Landmark>>> = Lazy::new(|| {
        let landmarks = LANDMARKS.lock().unwrap();
        let mut map = HashMap::new();
        for (landmark, (flag_id, _)) in landmarks.iter() {
            map.insert(*flag_id, *landmark);
        }
        Mutex::new(map)
    });

    impl Landmark {
        /// Get the flag ID for this landmark
        pub fn flag_id(&self) -> u32 {
            let landmarks = LANDMARKS.lock().unwrap();
            landmarks.get(self).map(|(id, _)| *id).unwrap_or(0)
        }

        /// Get the display name for this landmark
        pub fn name(&self) -> &'static str {
            let landmarks = LANDMARKS.lock().unwrap();
            landmarks.get(self).map(|(_, name)| *name).unwrap_or("Unknown")
        }

        /// Look up a landmark by its flag ID
        pub fn from_flag_id(flag_id: u32) -> Option<Landmark> {
            let by_flag = LANDMARK_BY_FLAG.lock().unwrap();
            by_flag.get(&flag_id).copied()
        }

        /// Get all landmarks as a vector
        pub fn all() -> Vec<Landmark> {
            let landmarks = LANDMARKS.lock().unwrap();
            landmarks.keys().copied().collect()
        }

        /// Get total number of landmarks
        pub fn count() -> usize {
            let landmarks = LANDMARKS.lock().unwrap();
            landmarks.len()
        }
    }
}
