// TODO(architecture-deepening, workstream A): this subtree-wide allow is still in
// place, deliberately. Lifting it yields ~91 warnings, overwhelmingly unused
// accessors on generated tables and view-state helpers — a lower-signal job than
// the read path (vm/, save/common/, util/), which was swept on 2026-07-22. See
// docs/ARCHITECTURE-DEEPENING.md.
#![allow(dead_code)]
pub mod item_name;
pub mod weapon_name;
pub mod armor_name;
pub mod aow_name;
pub mod accessory_name;
pub mod map_name;
pub mod graces;
pub mod whetblades;
pub mod cookbooks;
pub mod maps;
pub mod bosses;
pub mod inventory_verification;
pub mod summoning_pools;
pub mod colosseums;
pub mod regions;
pub mod classes;
pub mod stats;
pub mod weapons;
pub mod armors;
pub mod aows;
pub mod talismans;
pub mod items;
pub mod spells;
pub mod npcs;
pub mod shop_items;
pub mod world_pickups;
pub mod pickup_flags;
pub mod pickup_data;
pub mod dungeon_pickups;
pub mod event_flags_db;
pub mod landmarks;
pub mod quest_chains;
// Database Explorer modules (originally generated by the removed Python lab; see docs/archive/PYTHON-LAB.md)
pub mod graces_data;
pub mod unified_items;
pub mod merchants_data;
pub mod bosses_data;
pub mod entity_relationships_data;
pub mod entity_relationships;